### ISSUE TITLE
Cant get the audio with video download

### ISSUE THREAD

**Issue by wasiqaftab** [norkunas/youtube-dl-php#10]
HI

sorry to bother you again. when i try to download the video i cant get the audio. any idea why and what i an doing wrong. i am following your example

regards
wasiq

**Comment by norkunas** [comment]
@wasiqaftab could you paste your code how do you use it?

**Comment by chr314** [comment]
i know this old but i reply for others 

'format' => 'bestvideo' change to 'format' => 'best'

best: Select best quality format represented by single file with video and audio
worst: Select worst quality format represented by single file with video and audio
bestvideo: Select best quality video only format (e.g. DASH video), may not be available
worstvideo: Select worst quality video only format, may not be available
bestaudio: Select best quality audio only format, may not be available
worstaudio: Select worst quality audio only format, may not be available
