### ISSUE TITLE
Failed to detect metadata file

### ISSUE THREAD

**Issue by 51101179** [norkunas/youtube-dl-php#105]
$dl = new YoutubeDl(['skip-download' => true
        ]);
        $dl->setDownloadPath('../public');
        try {
            $video = $dl->download('https://www.youtube.com/watch?v=fltYAdedaFY');
            echo $video->getTitle(); // Will return Phonebloks
            // $video->getFile(); // \SplFileInfo instance of downloaded file
        } catch (NotFoundException $e) {
            echo 'Video not found' . $e->getMessage();
        } catch (PrivateVideoException $e) {
            echo 'Video is private' . $e->getMessage();
        } catch (CopyrightException $e) {
            echo 'The YouTube account associated with this video has been terminated due to multiple third-party notifications of copyright infringement' . $e->getMessage();
        } catch (\Exception $e) {
            echo 'Failed to download' . $e->getMessage();
        }
I set up laravel site but getting error "Failed to detect metadata file". Please help

**Comment by norkunas** [comment]
I've tried to run your exact code and it works for me.

Are you sure that your `youtube-dl` binary is up to date?

Which php version do you use?

Could you add this debug line to YoutubeDl class at the start of `processDownload` method:
`var_dump($process->getOutput());
?`

**Comment by 51101179** [comment]
don't know why but  setBinPath resolve my problem. Thank you!
