### ISSUE TITLE
Download Progress Need Help

### ISSUE THREAD

**Issue by grappetite-tahir** [norkunas/youtube-dl-php#106]
This might help some others like me
This is my first try to implement youtube downloader or youtube to mp4/mp3 converter.

I like your project and it has some nice features. 

Below is my response after successfully downloaded the video into mp4 but I can't see the progress and it appears suddenly after browser request completed. you can download completed.

`Percentage: 0.0%; Size: 8.29MiB; Speed: 410.88KiB/s; ETA: 00:20Percentage: 0.4%; Size: 8.29MiB; Speed: 181.07KiB/s; ETA: 00:46Percentage: 0.7%; Size: 8.29MiB; Speed: 171.27KiB/s; ETA: 00:49Percentage: 1.5%; Size: 8.29MiB; Speed: 194.77KiB/s; ETA: 00:42Percentage: 3.0%; Size: 8.29MiB; Speed: 185.76KiB/s; ETA: 00:44Percentage: 5.1%; Size: 8.29MiB; Speed: 77.88KiB/s; ETA: 01:43Percentage: 6.1%; Size: 8.29MiB; Speed: 63.81KiB/s; ETA: 02:04Percentage: 6.7%; Size: 8.29MiB; Speed: 55.88KiB/s; ETA: 02:21Percentage: 7.5%; Size: 8.29MiB; Speed: 43.85KiB/s; ETA: 02:59Percentage: 7.7%; Size: 8.29MiB; Speed: 39.91KiB/s; ETA: 03:16Percentage: 8.1%; Size: 8.29MiB; Speed: 39.86KiB/s; ETA: 03:15Percentage: 8.4%; Size: 8.29MiB; Speed: 39.27KiB/s; ETA: 03:17Percentage: 8.8%; Size: 8.29MiB; Speed: 40.63KiB/s; ETA: 03:10Percentage: 9.4%; Size: 8.29MiB; Speed: 43.24KiB/s; ETA: 02:57Percentage: 10.8%; Size: 8.29MiB; Speed: 48.17KiB/s; ETA: 02:37Percentage: 13.4%; Size: 8.29MiB; Speed: 54.23KiB/s; ETA: 02:15Percentage: 14.8%; Size: 8.29MiB; Speed: 59.12KiB/s; ETA: 02:02Percentage: 17.4%; Size: 8.29MiB; Speed: 68.78KiB/s; ETA: 01:41Percentage: 22.7%; Size: 8.29MiB; Speed: 83.99KiB/s; ETA: 01:18Percentage: 26.3%; Size: 8.29MiB; Speed: 88.17KiB/s; ETA: 01:10Percentage: 31.7%; Size: 8.29MiB; Speed: 104.21KiB/s; ETA: 00:55Percentage: 38.9%; Size: 8.29MiB; Speed: 125.09KiB/s; ETA: 00:41Percentage: 51.6%; Size: 8.29MiB; Speed: 159.22KiB/s; ETA: 00:25Percentage: 62.8%; Size: 8.29MiB; Speed: 188.03KiB/s; ETA: 00:16Percentage: 76.3%; Size: 8.29MiB; Speed: 216.55KiB/s; ETA: 00:09Percentage: 85.0%; Size: 8.29MiB; Speed: 238.28KiB/s; ETA: 00:05Percentage: 100.0%; Size: 8.29MiB; Speed: 267.62KiB/s; ETA: 00:00Percentage: 0.0%; Size: 2.69MiB; Speed: 166.84KiB/s; ETA: 00:16Percentage: 37.1%; Size: 2.69MiB; Speed: 2.93MiB/s; ETA: 00:00Percentage: 74.2%; Size: 2.69MiB; Speed: 2.51MiB/s; ETA: 00:00Percentage: 100.0%; Size: 2.69MiB; Speed: 2.67MiB/s; ETA: 00:00`

Can someone help me that How i will keep tracking the progress in real time. I know I need to use some ajax for this. I can request the download via ajax but how do I call the progress code in ajax separately to track the progress bar etc.

here is my complete code with is working fine. except the above thing i need.

`<?php
require 'vendor/autoload.php';

use YoutubeDl\YoutubeDl;
use YoutubeDl\Exception\CopyrightException;
use YoutubeDl\Exception\NotFoundException;
use YoutubeDl\Exception\PrivateVideoException;

$dl = new YoutubeDl([
    'continue' => false, // force resume of partially downloaded files. By default, youtube-dl will resume downloads if possible.
    'format' => 'bestvideo[ext=mp4]+bestaudio[acodec=opus]',
    'recode-video'       => 'mp4',
    'postprocessor-args' => '-vcodec copy',
    'ffmpeg-location' => 'D:/youtube-dl/ffmpeg.exe',
]);
// For more options go to https://github.com/rg3/youtube-dl#user-content-options

$dl->setBinPath('D:/youtube-dl/youtube-dl');
$dl->setDownloadPath('D:/');
$dl->onProgress(function ($progress) {
    $percentage = $progress['percentage'];
    $size = $progress['size'];
    $speed = $progress['speed'] ?? null;
    $eta = $progress['eta'] ?? null;
    
    echo "Percentage: $percentage; Size: $size";
    if ($speed) {
        echo "; Speed: $speed";
    }
    if ($eta) {
        echo "; ETA: $eta";
    }
    // Will print: Percentage: 21.3%; Size: 4.69MiB; Speed: 4.47MiB/s; ETA: 00:01
});
try {
    $video = $dl->download('https://www.youtube.com/watch?v=oDAw7vW7H0c');
    //echo $video->getTitle(); // Will return Phonebloks
    //$video->getFile(); // \SplFileInfo instance of downloaded file
    // echo '<pre>';
    // print_r($video);
} catch (NotFoundException $e) {
    echo 'ok';
    // Video not found
} catch (PrivateVideoException $e) {
    echo 'ok';
    // Video is private
} catch (CopyrightException $e) {
    echo 'ok';
    // The YouTube account associated with this video has been terminated due to multiple third-party notifications of copyright infringement
} catch (\Exception $e) {
    echo 'oks';
    // Failed to download
}`

**Comment by norkunas** [comment]
To properly track in browser, your download script must run in background and save progress state somewhere and with ajax you could return that state.

**Comment by grappetite-tahir** [comment]
Thanks for such a quick reply.
I can run the script in background with Laravel queue jobs but the problem is that, how to run the specific code that you mentioned to track the download progress separately in different ajax request. Can you explain me further so I can get idea.
As I can see you posted your comments to someone else issue that we should keep the progress tracker code above the download code. So if I keep this code in separate request how then my code will know that I need to track that specific file progress.

**Comment by norkunas** [comment]
Your controller could save an unique ID in some storage along with the requested url to download, then you could dispatch the job to queue for download with that ID/URL and return the ID to UI.
Your queue when downloading could save updated state in your storage.
Finally you'd be able to make ajax requests to your progress endpoint with that ID to get the current progress.

**Comment by grappetite-tahir** [comment]
Okay thanks for the responses you are making to help me.
I need some more clarity on this issue.

I can see that there is no way to get the file info before download started. If there is any let me know so that I can get the file info and hence I can store that info in the database table with some tracking points like UNIQUE ID's with file destination and then send the download job to the queue so then i can make the ajax call to the file destination to track the if the file still in progress to completely download.

OR to get the file info I need to use any other library from official document of Youtube.

Thank you once again.

**Comment by norkunas** [comment]
Why do you need the file info before download? At the start it's enough to save some ID to give the response for UI to keep it informed about the download progress and when it's done you could respond with the file url to download. Your queue job can save the file info after download.

**Comment by grappetite-tahir** [comment]
Sorry that I failed to deliver my thoughts in a good way.
assume i get this id using uniqid() and saved it in database, but its not enough for me to track the progress of the file being downloading into my host folder. atleast i need the file name like xyz.mp4 what ever u suggest me to store.

**Comment by norkunas** [comment]
Why not? Your queue job handler would use that ID and update the progress in database from the onProgress callback.

**Comment by norkunas** [comment]
But really, for the proper real time updates it's better to use sockets :)

**Comment by grappetite-tahir** [comment]
Okay thanks for the prompt replies. I will get back to you if there is anything I need related to this and of course I'll share the steps that If I get it successfully done. so everyone like me can get idea of this thing. Thank you again for your prompt replies.

**Comment by norkunas** [comment]
No problem, good luck implementing it :)
