### ISSUE TITLE
Video Not Downloading..

### ISSUE THREAD

**Issue by akashtsitestrokes** [norkunas/youtube-dl-php#107]
I have installed this files and run the code,

Its not showing any error message and nothing.

After print the error,
Its shows the below error.

YoutubeDl\Exception\ExecutableNotFoundException Object ( [message:protected] => "youtube-dl" executable was not found. Did you forgot to add it to environment variables? Or set it via $yt->setBinPath('/usr/bin/youtube-dl'). [string:Exception:private] => [code:protected] => 0 [file:protected] => F:\Akash\htdocs\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php [line:protected] => 239 [trace:Exception:private] => Array ( [0] => Array ( [file] => F:\Akash\htdocs\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php [line] => 141 [function] => createProcess [class] => YoutubeDl\YoutubeDl [type] => -> [args] => Array ( [0] => Array ( [0] => https://www.youtube.com/watch?v=fV6Ms9EwMhc [1] => --no-playlist [2] => --ignore-config [3] => --write-info-json [4] => --continue [5] => --format=bestvideo ) ) ) [1] => Array ( [file] => F:\Akash\htdocs\akash\youtube.php [line] => 26 [function] => download [class] => YoutubeDl\YoutubeDl [type] => -> [args] => Array ( [0] => https://www.youtube.com/watch?v=fV6Ms9EwMhc ) ) ) [previous:Exception:private] => )

**Comment by norkunas** [comment]
So did you try to understand the error? ;-)
