### ISSUE TITLE
getFilesize not work

### ISSUE THREAD

**Issue by Mo-0hammed** [norkunas/youtube-dl-php#110]
Please fix bugs in some links or formulas. File size is not retrieved
Example: 
```
<?php 
require_once 'vendor/autoload.php';
use YoutubeDl\YoutubeDl;
$ArrayDownload = ['format' => 'bestvideo[height<=480][ext=mp4]+bestaudio[ext=m4a]/best[height<=480][ext=mp4]', 'output' => 'T_3gZWMum28' . '.%(ext)s'];
$ArrayDownload['skip-download'] = true;
$dl = new YoutubeDL($ArrayDownload);
$dl->setDownloadPath('/var/www/html/yt');
$video = $dl->download('https://www.youtube.com/watch?v=T_3gZWMum28');
echo (int)$video->getFilesize(); // 0
```

**Comment by norkunas** [comment]
You are retrieving data which was provided by `youtube-dl` tool itself and if it returns zero then you should probably submit bug to their repo. Or you could get this from `$video->getFile()->getSize()`

**Comment by Mo-0hammed** [comment]
Can you provide the bugs because I do not know enough information?

**Comment by norkunas** [comment]
Okay, I've checked this further.
In youtube extractor there is this code:
```
        def _extract_filesize(media_url):
            return int_or_none(self._search_regex(
                r'\bclen[=/](\d+)', media_url, 'filesize', default=None))
```
So in case filesize is not extractable it will return null. And (int) null casts to 0.
There is no bug at all on neither side.

**Comment by Mo-0hammed** [comment]
Oh thank you
