### ISSUE TITLE
Some Videos Are Not Downloadable

### ISSUE THREAD

**Issue by tahirafridi** [norkunas/youtube-dl-php#111]
Hello nice library and updated.

I have successfully implemented the library and I realised that some of the videos like the videos with Tickmark (verified channels) videos are not working in the library, but I've checked the same video on ytmp3.cc and its working fine. So what you will suggest me to do to make it in work.

Demo video: https://www.youtube.com/watch?v=3HzbI8xJXe4

My code snippet is:
```
$dl = new YoutubeDl([
            'continue'              => true,
            'format'                => "bestvideo[ext=mp4]+bestaudio[acodec=opus]", //"bestvideo[height<=720]+bestaudio/best"
            'recode-video'          => $request->media_type,
            'postprocessor-args'    => '-vcodec copy',
            'ffmpeg-location'       => env('FFMPEG_LOC'),
        ]);
        $dl->setBinPath(env('YOUTUBEDL_LOC'));
        $dl->setDownloadPath(env('DOWNLOAD_LOC'));

        try {
            $video = $dl->download($request->url);

            $title = $video->getFulltitle();
            $download_link = asset('yt/' . $video->getFile()->getBasename());

            $video = new Video;
            $video->title = $title;
            $video->download_link = $download_link;
            $video->youtube_url = $request->url;
            $video->media_type = "video";
            $video->save();

            $data = [
                'title'         => $title,
                'download_link' => $download_link,
            ];

            return response()->json([
                'status'    => 200,
                'data'      => $data,
            ], 200);
        } catch (NotFoundException $e) {
            return response()->json([
                'status'    => 404,
                'data'      => null,
            ], 404);
        } catch (PrivateVideoException $e) {
            return response()->json([
                'status'    => 404,
                'data'      => null,
            ], 404);
        } catch (CopyrightException $e) {
            return response()->json([
                'status'    => 404,
                'data'      => null,
            ], 404);
        } catch (\Exception $e) {
            return response()->json([
                'status'    => 404,
                'data'      => null,
            ], 404);
        }
    }
```

I can't see any log for this issue, its executing the last exception

**Comment by norkunas** [comment]
Hello, thank you for kind words.

I've tried to debug your code and I think the problem is `recode-video` option. If you would try to run the command directly in terminal you'd get probably something like `ERROR: Decoder (codec av1) not found for input stream #0:0`. If this is the case then you'd need to compile your ffmpeg with [AV1](https://trac.ffmpeg.org/wiki/Encode/AV1) codec.
If you just get conversion failed error then I'd probably try to change `format` video ext option based on request media type, because if you are requesting to recode into avi, then the ext should be also .avi, right? :)

For further debugging you could debug the exception you get or enable symfony process debugging (the second has an example in this library readme).

**Comment by tahirafridi** [comment]
In my case I've 3 media type options to entertain, mp4, webm and mp3 (only for audio)
so first 2 options are for videos mp4 and webm, 3rd is mp3 so i don't know from where avi cames from, may be the video is uploaded in avi format. but i m not good at CLI things but can you just me the CLI code which i will run in the terminal and i will show u the output. Thank you for such a fast reply.

**Comment by norkunas** [comment]
About `avi` I've just gave it to you as an example because youtube-dl can accept it

**Comment by norkunas** [comment]
For debugging part, see here: https://github.com/norkunas/youtube-dl-php#download-video
You'll need to uncomment the `$dl->debug` call

**Comment by tahirafridi** [comment]
Alright after enabling the debug code, I'm getting this log

`
ERR > WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
OUT > [youtube] 3HzbI8xJXe4: Downloading webpage
OUT > [youtube] Downloading just video 3HzbI8xJXe4 because of --no-playlist
OUT > [info] Writing video description metadata as JSON to: Pashto_new_song_2020_Meena_Kawal_Kho_Gul_Panra_Tapay_4k_latest_Music_Pashto_Ghazal_2020-3HzbI8xJXe4.info.json
ERR > WARNING: Requested formats are incompatible for merge and will be merged into mkv.
OUT > [download] Pashto_new_song_2020_Meena_Kawal_Kho_Gul_Panra_Tapay_4k_latest_Music_Pashto_Ghazal_2020-3HzbI8xJXe4.mkv has already been downloaded and merged
OUT > [ffmpeg] Converting video from mkv to mp4, Destination: Pashto_new_song_2020_Meena_Kawal_Kho_Gul_Panra_Tapay_4k_latest_Music_Pashto_Ghazal_2020-3HzbI8xJXe4.mp4
ERR > ERROR: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
{"status":401,"data":null}
`

**Comment by norkunas** [comment]
I'd say try to search about the `Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument` error. I'm not familiar with this so can't help further sorry.

**Comment by tahirafridi** [comment]
So I've tried everything related to the error, but its not working in the library but its working in the terminal direct youtube-dl, so its mean there is something wrong in the php wrapper, its giving the error on this exact video url, but some videos are working fine, i can see in my download folder, there is some files, .mp4 .mkv .webm etc, it should be just one single file that is .mp4 but some how the library is not merging the files to one file.

**Comment by tahirafridi** [comment]
I can see in library while using in localhost its working but on live server its not working, I have latest youtube-dl, ffmpeg on live server, while its working .mp3 audio file, but not to download video.

**Comment by norkunas** [comment]
Are there many differences between your localhost and server?

**Comment by tahirafridi** [comment]
I think difference is only the OS, localhost on windows 10 xampp with php 7.2 and remote server is Linux OS centos with php 7.2 and all the tools required to run your library, let me know if there is anything related to ffmpeg i need to upgrade, in windows i just just download the exe files and replace the old one with new one, but in Linux i need to run the ssh to run upgrade commands.

**Comment by tahirafridi** [comment]
`ERR > WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
OUT > [youtube] 3HzbI8xJXe4: Downloading webpage
OUT > [youtube] Downloading just video 3HzbI8xJXe4 because of --no-playlist
OUT > [info] Writing video description metadata as JSON to: Pashto_new_song_2020_Meena_Kawal_Kho_Gul_Panra_Tapay_4k_latest_Music_Pashto_Ghazal_2020-3HzbI8xJXe4.info.json
OUT > [download] Pashto_new_song_2020_Meena_Kawal_Kho_Gul_Panra_Tapay_4k_latest_Music_Pashto_Ghazal_2020-3HzbI8xJXe4.f401.mp4 has already been downloaded
OUT > 
[download] 100% of 309.34MiB
OUT > [download] Pashto_new_song_2020_Meena_Kawal_Kho_Gul_Panra_Tapay_4k_latest_Music_Pashto_Ghazal_2020-3HzbI8xJXe4.f140.m4a has already been downloaded
OUT > 
[download] 100% of 3.98MiB
[ffmpeg] Merging formats into "Pashto_new_song_2020_Meena_Kawal_Kho_Gul_Panra_Tapay_4k_latest_Music_Pashto_Ghazal_2020-3HzbI8xJXe4.mp4"
ERR > ERROR: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument`
I'm getting this one warning/error, see the line saying Merging formats into
this is the my code to generate the above log.
`$dl = new YoutubeDl([
            'continue'              => true,
            'format'                => "bestvideo[ext=mp4]+bestaudio[ext=m4a]",
            'recode-video'          => "mp4",
            'postprocessor-args'    => '-vcodec copy',
            'ffmpeg-location'       => env('FFMPEG_LOC'),
        ]);`

**Comment by tahirafridi** [comment]
`'format'  => "bestvideo[height<=480]+bestaudio/best[height<=480]",`
The above code solved my issue, this code only check the best version equal or less than 480p and the audio is automatic, so whatever audio is available for the version it will get it automatic before I was giving the extension hard coded which was causing the issue. but some how its solved out, and may be in future it will help some others.
