### ISSUE TITLE
file_get_contents - No such file or directory

### ISSUE THREAD

**Issue by Kondzio18** [norkunas/youtube-dl-php#113]
```

<b>Warning</b>:  file_get_contents(C:\xampp\htdocs\projekt\dl\3562153b8.info.json ): failed to open stream: No such file or directory in <b>C:\xampp\htdocs\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php</b> on line <b>192</b><br />
--
  | <br />
  | <b>Fatal error</b>:  Uncaught TypeError: trim() expects parameter 1 to be string, boolean given in C:\xampp\htdocs\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php:192
  | Stack trace:
  | #0 C:\xampp\htdocs\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php(192): trim(false)
  | #1 C:\xampp\htdocs\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php(162): YoutubeDl\YoutubeDl-&gt;processDownload(Object(Symfony\Component\Process\Process))
  | #2 C:\xampp\htdocs\find.php(54): YoutubeDl\YoutubeDl-&gt;download('https://www.you...')
  | #3 {main}
  | thrown in <b>C:\xampp\htdocs\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php</b> on line <b>192</b><br />


```
How fix this error? I can see created json file in folder.

**Comment by Rizayev** [comment]
vendor/norkunas/youtube-dl-php/src/YoutubeDl.php

`
protected function processDownload(Process $process): Video
    {


        if (!preg_match('/Writing video description metadata as JSON to:\s(.+)/', $process->getOutput(), $m)) {
            throw new YoutubeDlException('Failed to detect metadata file.');
        }


        $name = explode('.', $m[1]);
        $newJson = trim($name[0]);
        foreach (glob($this->downloadPath . "/*.json") as $jsonFile) {
            if (strpos($jsonFile, $newJson) !== false) {
                $m[1] = $jsonFile;
            }
        }
        $metadataFile = $this->downloadPath . DIRECTORY_SEPARATOR . basename(ltrim($m[1]));
        $videoData = $this->jsonDecode(trim(file_get_contents($metadataFile)));


        @unlink($metadataFile);
        if (!isset($this->options['skip-download']) || false === $this->options['skip-download']) {
            if (isset($this->options['extract-audio']) && true === $this->options['extract-audio']) {
                $file = $this->findFile($videoData['_filename'], implode('|', $this->allowedAudioFormats));
                $videoData['_filename'] = pathinfo($file, PATHINFO_BASENAME);
            } elseif (isset($this->options['recode-video'])) {
                $file = $this->findFile($videoData['_filename'], implode('|', self::RECODE_VIDEO_FORMATS));
                $videoData['_filename'] = pathinfo($file, PATHINFO_BASENAME);
            } elseif (preg_match('/merged into mkv/', $process->getErrorOutput())) {
                $videoData['_filename'] = pathinfo($this->findFile($videoData['_filename'], 'mkv'), PATHINFO_BASENAME);
            }

            $videoData['file'] = new \SplFileInfo($this->downloadPath . DIRECTORY_SEPARATOR . $videoData['_filename']);
        } else {
            $videoData['file'] = null;
        }

        return new Video($videoData);
    }
`

**Comment by Rizayev** [comment]
vendor/norkunas/youtube-dl-php/src/YoutubeDl.php

 `    protected function processDownload(Process $process): Video
    {


        if (!preg_match('/Writing video description metadata as JSON to:\s(.+)/', $process->getOutput(), $m)) {
            throw new YoutubeDlException('Failed to detect metadata file.');
        }


        $name = explode('.', $m[1]);
        $newJson = trim($name[0]);
        foreach (glob($this->downloadPath . "/*.json") as $jsonFile) {
            if (strpos($jsonFile, $newJson) !== false) {
                $m[1] = $jsonFile;
            }
        }
        $metadataFile = $this->downloadPath . DIRECTORY_SEPARATOR . basename(ltrim($m[1]));
        $videoData = $this->jsonDecode(trim(file_get_contents($metadataFile)));


        @unlink($metadataFile);
        if (!isset($this->options['skip-download']) || false === $this->options['skip-download']) {
            if (isset($this->options['extract-audio']) && true === $this->options['extract-audio']) {
                $file = $this->findFile($videoData['_filename'], implode('|', $this->allowedAudioFormats));
                $videoData['_filename'] = pathinfo($file, PATHINFO_BASENAME);
            } elseif (isset($this->options['recode-video'])) {
                $file = $this->findFile($videoData['_filename'], implode('|', self::RECODE_VIDEO_FORMATS));
                $videoData['_filename'] = pathinfo($file, PATHINFO_BASENAME);
            } elseif (preg_match('/merged into mkv/', $process->getErrorOutput())) {
                $videoData['_filename'] = pathinfo($this->findFile($videoData['_filename'], 'mkv'), PATHINFO_BASENAME);
            }

            $videoData['file'] = new \SplFileInfo($this->downloadPath . DIRECTORY_SEPARATOR . $videoData['_filename']);
        } else {
            $videoData['file'] = null;
        }

        return new Video($videoData);
    }`

**Comment by Rizayev** [comment]
Cyrillic letters are not supported

**Comment by norkunas** [comment]
Could you share the URL you use for download?

**Comment by Kondzio18** [comment]
For example: https://www.cda.pl/video/49173613c

`<?php
require __DIR__ . '/vendor/autoload.php';

use YoutubeDl\YoutubeDl;
use YoutubeDl\Exception\CopyrightException;
use YoutubeDl\Exception\NotFoundException;
use YoutubeDl\Exception\PrivateVideoException;

$dl = new YoutubeDl([
    'cookies' => 'c:\xampp\htdocs\cookies\cookies.txt',
	'skip-download' => true,
	'write-thumbnail' => true,
	'output' => 'asad',
	'no-warnings' => false,
]);


$dl->setBinPath('c:\xampp\htdocs\projekt\yt-dl-new.exe');
$dl->setDownloadPath('c:\xampp\htdocs\new_dl');


try {
    $video = $dl->download('hereurl');
	
	
	
    echo $video->getTitle(); // Will return Phonebloks
    echo "<a href='".$video->getUrl()."'>kliknij</a>";
	
	
	// $video->getFile(); // \SplFileInfo instance of downloaded file
} catch (NotFoundException $e) {
    echo $e;
} catch (PrivateVideoException $e) {
    echo $e;
} catch (CopyrightException $e) {
    echo $e;
} catch (\Exception $e) {
    echo $e;
}

?>`

**Comment by Rizayev** [comment]
Cyr

> For example: https://www.cda.pl/video/49173613c
> 
> ```
> <?php
> require __DIR__ . '/vendor/autoload.php';
> 
> use YoutubeDl\YoutubeDl;
> use YoutubeDl\Exception\CopyrightException;
> use YoutubeDl\Exception\NotFoundException;
> use YoutubeDl\Exception\PrivateVideoException;
> 
> $dl = new YoutubeDl([
>     'cookies' => 'c:\xampp\htdocs\cookies\cookies.txt',
> 	'skip-download' => true,
> 	'write-thumbnail' => true,
> 	'output' => 'asad',
> 	'no-warnings' => false,
> ]);
> 
> 
> $dl->setBinPath('c:\xampp\htdocs\projekt\yt-dl-new.exe'); //compiled by pyinstaller; works with command window
> $dl->setDownloadPath('c:\xampp\htdocs\new_dl');
> 
> 
> try {
>     $video = $dl->download('hereurl');
> 	
> 	
> 	
>     echo $video->getTitle(); // Will return Phonebloks
>     echo "<a href='".$video->getUrl()."'>clickme</a>";
> 	
> 	
> 	// $video->getFile(); // \SplFileInfo instance of downloaded file
> } catch (NotFoundException $e) {
>     echo $e;
> } catch (PrivateVideoException $e) {
>     echo $e;
> } catch (CopyrightException $e) {
>     echo $e;
> } catch (\Exception $e) {
>     echo $e;
> }
> 
> ?>
> ```
> 
> I noticed the error after adding setBinPath

cyrillic' is not a supported

try it
vendor/norkunas/youtube-dl-php/src/YoutubeDl.php
method processDownload()

$name = explode('.', $m[1]);
    $newJson = trim($name[0]);
    foreach (glob($this->downloadPath . "/*.json") as $jsonFile) {
        if (strpos($jsonFile, $newJson) !== false) {
            $m[1] = $jsonFile;
        }
    }
    $metadataFile = $this->downloadPath . DIRECTORY_SEPARATOR . basename(ltrim($m[1]));
    $videoData = $this->jsonDecode(trim(file_get_contents($metadataFile)));

**Comment by Kondzio18** [comment]
Thank you! It works!!!!

**Comment by norkunas** [comment]
@Kondzio18  @Rizayev These changes will be lost if you'll fetch future package updates.
For me it properly works on Ubuntu 18.04. Which PHP version do you use?

**Comment by Rizayev** [comment]
> @Kondzio18 @Rizayev These changes will be lost if you'll fetch future package updates.
> For me it properly works on Ubuntu 18.04. Which PHP version do you use?

I know =)
7.1,7.2
