### ISSUE TITLE
`Format::getFormatId` returns the whole format, not just the ID

### ISSUE THREAD

**Issue by phollweck** [norkunas/youtube-dl-php#115]
When you call `Format::getFormatId()` I expected to get just the ID of the Format not the whole format string.

I think this is just a simple typo, since it returns the same thing as `Format::getFormat()`

Relevant lines:
- [`Format::getFormat()`](https://github.com/norkunas/youtube-dl-php/blob/2009bdec31ca257d6b4103147f6a63e25ac07da6/src/Entity/Format.php#L14)
- [`Format::getFormatId()`](https://github.com/norkunas/youtube-dl-php/blob/2009bdec31ca257d6b4103147f6a63e25ac07da6/src/Entity/Format.php#L94)

![image](https://user-images.githubusercontent.com/54676904/79344506-3a360d00-7f30-11ea-892c-f77f22f10019.png)

Other than that, the library worked great! Thanks for the work :)

**Comment by norkunas** [comment]
Hello @phollweck,

I've checked the code and yes it's a typo. Would you like to contribute and submit a Pull Request to fix this?

**Comment by phollweck** [comment]
Sure, [pull request created](https://github.com/norkunas/youtube-dl-php/pull/116) :)
