### ISSUE TITLE
Can't you add in example?

### ISSUE THREAD

**Issue by ttodua** [norkunas/youtube-dl-php#119]
It's necessary part for the script to work:

for python:
```
   $dl->setPythonPath(..);
   $dl->setBinPath(__DIR__.'/youtube-dl');
```

for windows:
`  $dl->setBinPath(__DIR__.'/youtube-dl.exe');`

cant you add that in readme examples?

**Comment by norkunas** [comment]
I'm sorry, but it's not necessary. If you would read the first step, its explained:
> First step is to download the youtube-dl and add it's path to environment variables.
So if you would add `youtube-dl` as environment variable, you wouldn't need set the binary path :)
Also with python path it's a workaround when it doesn't work but should, personally I didn't need to set it never.
Also you could contribute and add these examples :)

**Comment by ttodua** [comment]
`First step is to download the youtube-dl and add it's path to environment variables.`

it says, but this statement is not complete. What I mean:
1) How to add path to environment variables? that needs a bit headache for newcomer, especially searching googles and doing this or that. moreoever, what if we just use that on VPS, instead of windows (where I know how to add environment variables)? that needs another googling and terminal commands executing. Why that many trouble? just addition of 3 extra words there would be nice:

First step is to download the youtube-dl and add it's path to environment variables (or set it in code `$dl->setBinPath('./path-to/youtube-dl');` ):.

that will help many (like me). about python path, ok,you might ignore.

**Comment by norkunas** [comment]
Okay, I agree that it could be a headache for newcomers. But if you learned this the hardway, why not to contribute then by yourself to help others? :)
