### ISSUE TITLE
ERROR: unable to rename file: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by jhemmmm** [norkunas/youtube-dl-php#122]
I am receiving quite a lot of this error.
![image](https://user-images.githubusercontent.com/14343151/82937766-4b5c4a00-9fc3-11ea-955f-b8d0bd00f188.png)

**Comment by norkunas** [comment]
I'm not sure we can do something here, because this error comes itself from the `youtube-dl` binary and not from the library.
