### ISSUE TITLE
not work methods

### ISSUE THREAD

**Issue by labi-le** [norkunas/youtube-dl-php#123]
not work getUploadDate, not work getThumbnails, getLikeCount, getDislikeCount

**Comment by labi-le** [comment]
![Screenshot_20200615_225534](https://user-images.githubusercontent.com/65619560/84695113-620b1680-af5b-11ea-9f37-1966df4f1563.jpg)

**Comment by norkunas** [comment]
@labi-le could you be more clear about this? What configuration did you use? From your dumped data I see that `youtube-dl` binary returned like/dislike count as empty strings, but for me it works properly:
![image](https://user-images.githubusercontent.com/2722872/84735235-aaeabb80-afab-11ea-819c-7fc8a03934c4.png)

**Comment by labi-le** [comment]
> @labi-le could you be more clear about this? What configuration did you use? From your dumped data I see that `youtube-dl` binary returned like/dislike count as empty strings, but for me it works properly:
> ![image](https://user-images.githubusercontent.com/2722872/84735235-aaeabb80-afab-11ea-819c-7fc8a03934c4.png)

 I don't know why, but it worked on its own
