### ISSUE TITLE
how do I output onProgress in real time ?

### ISSUE THREAD

**Issue by labi-le** [norkunas/youtube-dl-php#124]

**Comment by norkunas** [comment]
You could use https://mercure.rocks/ or websockets.

**Comment by Zakirzhan** [comment]
> _No description provided._

did it work?

**Comment by Zakirzhan** [comment]
> You could use https://mercure.rocks/ or websockets.

how to use this with php?

**Comment by norkunas** [comment]
@Zakirzhan there is a package https://github.com/ntavelis/mercure-php for this

**Comment by Zakirzhan** [comment]
Can you help me to make it for money in my server?

**Comment by norkunas** [comment]
@Zakirzhan sure, but maybe 1-2 weeks later. Please send me an email, describing what you already have and what needs to be done.

**Comment by Zakirzhan** [comment]
> r. Please send me an email, describing what you already have and what needs to be done.

I couldn't find your email address, please send me your address

**Comment by norkunas** [comment]
It's in the `composer.json` file
