### ISSUE TITLE
LC_ALL error

### ISSUE THREAD

**Issue by promotion** [norkunas/youtube-dl-php#126]
Hi again, 
I know theres quite some information about LC_ALL out there, but maybe you'll advice how to fix my case . 

I have Ubuntu 18 , and trying to save OK and VK videos which would lack russian letters in filename. 

When downloading it would show warning :

```ERR > WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.```

I have tried recompiling locales , and it shows :

```
root@vps# locale
LANG=ru_RU.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

Also in /etc/etnviroment : 
```
LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8
```

But russian chars are not appearing on filename - so im getting filenames like _-87687687686.mp4 . Any suggestion how this could be fixed ? I assume maybe LC_ALL should be set for Pyton in some other config files somehow ?

Thanks !

**Comment by norkunas** [comment]
Hi, it's strange because I use Ubuntu 18 (for my desktop) and as you can see in your previous issue my the filename was with russian letters..

Looking at the ytdl source there is this check:
``
        if (sys.platform != 'win32'
                and sys.getfilesystemencoding() in ['ascii', 'ANSI_X3.4-1968']
                and not params.get('restrictfilenames', False)):
```
So I'd suggest you to somehow debug why your file system encoding matches this condinition.. Or then try to open an issue in that library.
Also: did you run `source /etc/environment` after editing it? And keep in mind that editing /etc/environment this changes the env variables for all users in your vps (https://askubuntu.com/a/866169).

**Comment by norkunas** [comment]
Closing as there is no feedback.
