### ISSUE TITLE
example of  /usr/bin/youtube-dl in windows ?

### ISSUE THREAD

**Issue by xiisaiki** [norkunas/youtube-dl-php#127]
i have the same problem 
    "message": "\"youtube-dl\" executable was not found. Did you forgot to add it to environment variables? Or set it via $yt->setBinPath('/usr/bin/youtube-dl')."

i add this to environnement variables , im not sure if it's right but i add the variable and it's path to executable folder

 i run it with cmd so it works  but i dont know where exactly put  $yt->setBinPath('/usr/bin/youtube-dl') so i could run it with php

and where this path in windows ?? im running wamp btw

please help me !!

**Comment by norkunas** [comment]
Hello,
You can store the `youtube-dl` binary anywhere and then after initializing the `YoutubeDl` instance from this library you can call the `setBinPath`, for example:

```
<?php
require __DIR__ . '/vendor/autoload.php';

use YoutubeDl\YoutubeDl;

$dl = new YoutubeDl([
    'continue' => true,
    'format' => 'bestvideo',
]);
$dl->setBinPath('C:/Users/xiisaiki/youtube-dl.exe');
```

**Comment by xiisaiki** [comment]
hello dear friend  , thank you for your replay

i just made it somehow , i add id on convert.php line in this peace of code

`	if(!$exists)
	{
		if($format == 'mp3')
		{
			$options = array(
				'extract-audio' => true,
				'audio-format' => 'mp3',
				'audio-quality' => 0,
				'output' => '%(id)s.%(ext)s',
				//'ffmpeg-location' => '/usr/local/bin/ffmpeg'
			);
		}
		else
		{
			$options = array(
				'continue' => true,
				'format' => 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best',
				'output' => '%(id)s.%(ext)s'
			);
		}

		$dl = new YoutubeDl($options);
		$dl->setDownloadPath(DOWNLOAD_FOLDER);
		$dl->setBinPath('C:\wamp\www\website\wev\youtube-dl.exe');
	}
`
the error changed to : "message": "Unable to launch a new process.",

just for infos : i installed michaelbelgium/youtube-to-mp3 via composer then i added this via cmd composer
`composer require norkunas/youtube-dl-php`

then the full project installed on my wamp server so i added youtube-dl.exe in my environnement vars

so what im missing here , please any suggestions ?

**Comment by norkunas** [comment]
So you should debug why your php env can't launch a new process.
Some suggestions where to look:
 - check if `proc_open` function is not disabled
 - check if your DOWNLOAD_FOLDER is writable.

**Comment by xiisaiki** [comment]
hello brother , wow this is so much complicated !

just checked my php.ini and found this
 
; This directive allows you to disable certain functions for security reasons.
; It receives a comma-delimited list of function names.
; http://php.net/disable-functions
disable_functions =

i think in my case , i have no disabled functions in my localserver including proc_open
second check was about checking writable folder , im not sure but i think it's writable because i changed it's attributes 

i'm really stuck at this point

**Comment by norkunas** [comment]
Then you should somehow debug symfony process code where it tries to start the process with `proc_open` function why it's failing.

**Comment by xiisaiki** [comment]
thanks bro i solved this by giving the real path of downloads folder
define("DOWNLOAD_FOLDER", "/path/to/downloads/");

now im just facing this 

The command "path/to/youtube-dl.exe "https://www.youtube.com/watch?v=HCRlcxKnruE" --no-playlist --ignore-config --write-info-json --extract-audio --audio-format=mp3 --audio-quality=0 "--output="^%"(id)s."^%"(ext)s"" failed. Exit Code: 1(General error) Working directory: path/to/downloads/ Output: ================ [youtube] HCRlcxKnruE: Downloading webpage [youtube] Downloading just video HCRlcxKnruE because of --no-playlist [youtube] HCRlcxKnruE: Downloading MPD manifest [info] Writing video description metadata as JSON to: HCRlcxKnruE.info.json [download] HCRlcxKnruE.webm has already been downloaded [download] 100% of 2.50MiB Error Output: ================ ERROR: ffprobe/avprobe and ffmpeg/avconv not found. Please install one.
--

**Comment by norkunas** [comment]
So you need to setup the ffmpeg/acvonv if you are converting video to audio

**Comment by norkunas** [comment]
Closing as there is no feedback.
