### ISSUE TITLE
Faild to download

### ISSUE THREAD

**Issue by Dosshu** [norkunas/youtube-dl-php#130]
I am trying to run it. but getting this error, 
Faild to download
![faisalvai](https://user-images.githubusercontent.com/38270186/87145783-acb64f00-c2cb-11ea-8783-6af5145f6fb8.JPG)

**Comment by norkunas** [comment]
So you should properly handle the exception to see the message, it's just an example code :)

**Comment by norkunas** [comment]
Are you sure that `H:\Yt` is the executable binary file and not the directory?

**Comment by norkunas** [comment]
Also try to configure abslute download path to check if it works (make sure that it exists) :)

**Comment by Dosshu** [comment]
Please correct my problem, i am learning.
`$dl->setBinPath('H:\yt\youtube-dl.exe');

$dl->setPythonPath('C:\Python\python.exe');

$dl->setDownloadPath('H:\down');
`
Errom meessage : Message :The command "C:\Python\python.exe H:\yt\youtube-dl.exe "https://www.youtube.com/watch?v=oDAw7vW7H0c" --no-playlist --ignore-config --write-info-json --continue --format=bestvideo" failed. Exit Code: 1(General error) Working directory: H:\down Output: ================ Error Output: ================ C:\Python\python.exe: can't find '__main__' module in 'H:\\yt\\youtube-dl.exe'

**Comment by Dosshu** [comment]
> Are you sure that `H:\Yt` is the executable binary file and not the directory?

What is binary file means? is it "youtube-dl.exe"?

**Comment by Dosshu** [comment]
> Also try to configure abslute download path to check if it works (make sure that it exists) :)
After setting this  `$dl->setDownloadPath('down/');`  ) i am getting this message "Message :Unable to launch a new process."

**Comment by Dosshu** [comment]
Thank you, Finally i solve the problem, we should use absolute path,
