### ISSUE TITLE
Output to php tmpfile

### ISSUE THREAD

**Issue by reesericci** [norkunas/youtube-dl-php#131]
Is it possible to have the video get downloaded to a php tempfile?

**Comment by reesericci** [comment]
@norkunas Anyone?

**Comment by reesericci** [comment]
@norkunas is anyone gonna look at this issue?

**Comment by norkunas** [comment]
Hi, and sorry, I am on holiday and will be back on july 27

**Comment by norkunas** [comment]
Hello @reesericci,

What's your use case for this?

**Comment by reesericci** [comment]
Sorry for the late reply, I'm trying to create a youtube-dl downloader website.I want to use a tmpfile to download the video to, save it to the user's computer, then delete the tmpfile. Also, this approach would allow me to never have overlapping video names.

Is there a better way?

**Comment by norkunas** [comment]
I'm not sure that `youtube-dl` binary itself supports this.

You can consider downloaded file to be as a tmpfile if you'll return it for user and after that will just remove manually. You can use output template option with your random generated to avoid overlapping.

Another option would be to use `skip-download` option, then taking the url from returned formats and then return the contents to download directly from that url.

**Comment by reesericci** [comment]
ok, closing now
