### ISSUE TITLE
PHP Warning:  Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by jack90886** [norkunas/youtube-dl-php#134]
When trying to get the categories of a video I would sometimes get "Warning:  Invalid argument supplied for foreach()" This only happens on other youtube-dl supported sites not YouTube, as far as I'm aware.

I added a line of code to check if categories is an array, prior to the foreach to fix it. Could this fix be added so it's not overwritten when recompiling?

```
   public function getCategories()
    {
		
		$categories = [];
		
		if(\is_array($this->get('categories'))){
	
			foreach ($this->get('categories') as $title) {
				$categories[] = new Category(['title' => $title]); // BC
			}
			
		}

        return $categories;
    }
```

**Comment by norkunas** [comment]
@jack90886 I've released bugfix as v1.6.1, can you check if it works for you?

**Comment by jack90886** [comment]
Works perfectly, thanks for the great work you do.

**Comment by norkunas** [comment]
I'm glad :+1: Please give it a try with `dev-master` version, trying to align this library with `youtube-dl` capabilities :slightly_smiling_face:
