### ISSUE TITLE
Proxy for whole wrapper

### ISSUE THREAD

**Issue by promotion** [norkunas/youtube-dl-php#135]
Hi was doing download fomr soundcloud, and ralised that proxy wasnt used for all functions . 

```
 $dl = new YoutubeDl([
            'continue' => true, 
            'restrict-filenames' => true,
            'proxy' => $this->myproxy,
            'no-check-certificate'=>true,
            "no-mtime"=>true,
            "geo-bypass"=>true
            

]);
```

However inside the YoutubeDL.php file, the getInfo would not use the proxy at all . 

I had to rewrite it to pass proxy manually, and add it to parameters list, in order for proxy to be implemented. 

```
$process = $this->createProcess([
            $url,
            '-j',
            '--no-playlist',
            '--ignore-config',
            '--proxy',
            $proxy
]);
```

Could you please somehow fix the lib so that any place would be using proxy ? 

Thanks !

**Comment by norkunas** [comment]
Hello,

proxy is a defined option so it should be added on this line: https://github.com/norkunas/youtube-dl-php/blob/1.x/src/YoutubeDl.php#L137

**Comment by norkunas** [comment]
If this really doesn't work, then a better solution would be to override the `createProcess` method and then always add `proxy => *` to the arguments list.

**Comment by promotion** [comment]
Hi, 
Sorry, i see that getInfo process is funciton written by some other coder :) 

Maybe you have plans on getting playlists info as JSON + separate items just as JSON info rather then download ? (youtube-dl has this on board , but seems this functionality was missing some time ago when we started our project :) )

**Comment by norkunas** [comment]
I am currently in progress of making v2 which supports playlists. I don't see the point then of using this wrapper if you are not targeting downloads.. You can instantiate process directly and then get the json.. Or just extend the library main class with another method to retrieve info's instead of downloading..
