### ISSUE TITLE
Pass chunked download to client

### ISSUE THREAD

**Issue by promotion** [norkunas/youtube-dl-php#137]
Hi, 

Im now running your wrapper in a way i donwload a file - store it on disk , and then someone can come and download the file form disk . 

I saw recently that youtube-dl supports streaming, so my question - maybe it is possible to push the downloaded chunks one by one to clients download file ?  Thus i can do smth like (showing exact format  i need + stream it to stdout)

"youtube-dl  -f 18 https://www.youtube.com/watch?v=nGdFHJXciAQ -o -"

Can your wrapper grab this chunk by chunk and push as download via PHP/APACHE ?

(Or any other way i can use not to save the file localy but send it for download

Thanks

**Comment by norkunas** [comment]
Hello, this lib primary was made for downloading.. :)
If you want to stream video, you could also use `skip-download` option, then grab the appropriate format url from the returned metadata and then stream it.

**Comment by promotion** [comment]
Yes, i understand its more for downloading, and my question is exactly about downloading as well :)
What i mean - The scripts where i found reference to your lib where mostly about SAVING the file on SERVERSIDE so that file could be DOWNLOADED  from server to any PC. 
So what i thought it would be cool if you lib could not only SAVE the file to disk, but also push it to output chunk by chunk, so file could be saved on CLIENT PC (piece by piece, without saving full file on server first.). 
In fact this could be achieved just by getting download link from youtube-dl , and then grabbing it with CURL by chunks , and PUSHING to download on client side. But i played with this a bit , and i see that DOWNLAOD SPEED of youtube-dl is much faster than CURL , plus this would avoid a need of getting link URL, and working with it +CURL/chunks (Thus Youtube-dl could push directly to DOWNLOAD on client side. If this is possible of course :) )

I know it's outside the scope of simple wrapper  and is kinda extra functionality, but this would be really cool extra functionality :)

**Comment by norkunas** [comment]
If you'd like to see this in library, maybe you could contribute and submit pull request :) but how would it behave if multiple urls would be passed?

**Comment by promotion** [comment]
Have no idea about multiple urls -as for my purposes only 1 URL was needed :)
