### ISSUE TITLE
NoDownloadPathProvidedException using dev-master branch

### ISSUE THREAD

**Issue by vesper8** [norkunas/youtube-dl-php#138]
I installed the dev-master as suggested and followed the example for converting a song to mp3 and was receiving this error: `Missing configured downloadPath option`

I dug into the code and replaced

```
            Options::create($downloadPath)
```

by

```
            Options::create()
                ->downloadPath($downloadPath)
```

And now it works

So documentation should be updated. It seems the Options constructor in the dev-master does nothing

**Comment by norkunas** [comment]
Hello, would you like to contribute?

**Comment by vesper8** [comment]
I've got so much on my plate right now.. as I'm sure you do.. reporting issues is my way of contributing for the most part.. I do the occasional PR as well.. I'm just starting to integrate this into my project and have been using youtube-dl from the CLI for years now. If I come across any other issues or anything that would require a PR I will add it

**Comment by norkunas** [comment]
I've fixed it now, thanks for reporting :)
