### ISSUE TITLE
ProcessBuilderInterface ERROR

### ISSUE THREAD

**Issue by xPiston** [norkunas/youtube-dl-php#139]
Hello, after several tries I always make the same erro no matter what I do, here is the error:      9  [Sat Nov 21 16:30:19.720451 2020] [php7:emerg] [pid 27160] [client 37.164.58.233:20526] PHP Parse error:  syntax error, unexpected 'ProcessBuilderInterface' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /var/www/html/YT/siteYoutube/vendor/norkunas/youtube-dl-php/src/YoutubeDl.php on line 39

**Comment by norkunas** [comment]
Hello, which version of PHP do you have?

**Comment by fabienlege** [comment]
same error with php 7.3.26

**Comment by norkunas** [comment]
Are you ignoring platform reqs? Because this library requires php 7.4
