### ISSUE TITLE
I am unable to install the project via composer. "composer require norkunas/youtube-dl-php:dev-master"

### ISSUE THREAD

**Issue by hirazzz** [norkunas/youtube-dl-php#143]
I am using php 7.4 version. When i try to install "composer require norkunas/youtube-dl-php:dev-master" in my my xampp/htdocs then the following errors shows on CMD:
  [InvalidArgumentException]
  Package norkunas/youtube-dl-php at version dev-master has a PHP requirement incompatible with your PHP version, PHP
   extensions and Composer version. Using the Php version 7.4.

**Comment by norkunas** [comment]
@hirazzz maybe your fpm version differs from cli?
