### ISSUE TITLE
No audio in downloaded videos

### ISSUE THREAD

**Issue by RiversideRocks** [norkunas/youtube-dl-php#145]
I am using the stable version of this wrapper. However, the videos that are downloaded have no sound. How can I fix this?

**Comment by norkunas** [comment]
I'd say you need to select the format then, probably for some reason the binary chooses to download without sound. I guess you download from YouTube?

**Comment by RiversideRocks** [comment]
Is there a way to set an option for sound? What are the valid formats that can be set?

```
$dl = new YoutubeDl([
    'continue' => true,
    'format' => 'bestvideo', // Can this be set to "sound"?
]);

**Comment by norkunas** [comment]
Basically you can just set anything what `youtube-dl` binary accepts.
See https://github.com/ytdl-org/youtube-dl/blob/master/README.md#format-selection for more info.

**Comment by RiversideRocks** [comment]
Ah ok, that makes sense, the default looks like webm, I'll change it to mp4 and see what happens.
