### ISSUE TITLE
Fatal error: Uncaught Error: Class 'YoutubeDl\Options' not found

### ISSUE THREAD

**Issue by Kuzoto** [norkunas/youtube-dl-php#146]
I keep getting Fatal error: Uncaught Error: Class 'YoutubeDl\Options' not found in /home/customer/www/spotify.crystallizedimagination.com/public_html/youtube2mp3.php:13
<?php

declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

use YoutubeDl\Options;
use YoutubeDl\YoutubeDl;

$link = $_POST['id'];
$yt = new YoutubeDl();
$collection = $yt->download(
    Options::create()
        ->downloadPath('https://spotify.crystallizedimagination.com/videos/')
        ->extractAudio(true)
        ->audioFormat('mp3')
        ->audioQuality(0) // best
        ->output('%(title)s.%(ext)s')
        ->url($link)
);

foreach ($collection->getVideos() as $video) {
    if ($video->getError() !== null) {
        echo "Error downloading video: {$video->getError()}.";
    } else {
        $video->getFile(); // audio file
    }
}
?>
Are my files in the wrong locations or something? I'm not sure how to fix this error.

**Comment by norkunas** [comment]
Try to check if composer is properly dumped the classes to autoload

**Comment by Kuzoto** [comment]
It seems to because it isnt returning that error for use YoutubeDl/YoutubeDl, but ill give it a shot

**Comment by Kuzoto** [comment]
heres the composer.json file
{
    "require": {
        "jwilsson/spotify-web-api-php": "^4.2",
        "norkunas/youtube-dl-php": "^1.6"
    }
}
I re-ran composer-dump autoload and it is still returning the same error message. I'm not sure where to look.

**Comment by norkunas** [comment]
Sorry, currently I'm afk, will try your script when I could and will get back to you.

**Comment by Kuzoto** [comment]
No worries. Thanks for the help!

**Comment by norkunas** [comment]
Hello.
I guess you have installed the previous version of the library, while the documentation explicitly says it is for unreleased version yet :)

**Comment by Kuzoto** [comment]
ill give it a shot

**Comment by Kuzoto** [comment]
It keeps returning this error and I'm not sure what to do because when I try to update Composer it says its a read-only file and when I check my php versions its greater than the one in the requirements(I have version 7.3.27 and yours says >= 7.0.8). I am using this on a shared server, so that may have something to do with it.
```
[InvalidArgumentException]
  Package norkunas/youtube-dl-php at version dev-master has a PHP requirement
  incompatible with your PHP version, PHP extensions and Composer version
```

**Comment by norkunas** [comment]
Master branch requires at least php7.4 :) Otherwise then you should read the documentation for v1

**Comment by Kuzoto** [comment]
i just saw that :)

**Comment by Kuzoto** [comment]
sorry I'm really blind sometimes. Thank you for the help, I really appreciate it.

**Comment by norkunas** [comment]
No problem :)
