### ISSUE TITLE
Download progress with external downloader

### ISSUE THREAD

**Issue by mirdoraghi** [norkunas/youtube-dl-php#147]
How can I use onProgress method with external downloader like aria2c ?

**Comment by norkunas** [comment]
I'm not sure as I didn't have any use case to use external downloader :confused:

**Comment by mirdoraghi** [comment]
The output is different when external downloader is used than when it is not.
See the output.

![image](https://user-images.githubusercontent.com/44964722/112110698-e6688500-8bd0-11eb-934f-52f0804067b7.png)

**Comment by norkunas** [comment]
Maybe you could try then to use a custom callback for `debug` function to try parsing it's progress.
