### ISSUE TITLE
fatal TypeError on downloading

### ISSUE THREAD

**Issue by Oreolek** [norkunas/youtube-dl-php#148]
> Argument 1 passed to YoutubeDl\YoutubeDl::YoutubeDl\{closure}() must be of the type string, null given, called in `vendor/norkunas/youtube-dl-php/src/YoutubeDl.php` on line 139

I'm using the 2.0 version. Fails on using https://youtu.be/ domain.

**Comment by norkunas** [comment]
Could you include your calling code?

**Comment by Oreolek** [comment]
Hmm, fails on drive.google.com too. Code:

      $dl = new YoutubeDl();
      $options = Options::create()
        ->downloadPath($folder)
        ->url($remote_url);
      $collection = $dl->download($options);

**Comment by norkunas** [comment]
Guessing from your error for some reason `$progress` callback is not set and when it tries to output the progress it fails because it's null.
Could you check if it would work if you define:
```
$dl->onProgress(function () {});
```
?

**Comment by Oreolek** [comment]
yup, that's better now
