### ISSUE TITLE
meta data not found 0_0

### ISSUE THREAD

**Issue by stepan-neretin7** [norkunas/youtube-dl-php#150]
Centos 7
Warning: file_get_contents(data/_-aZPis50uvF4.info.json): failed to open stream: No such file or directory in /usr/share/nginx/html/vendor/norkunas/youtube-dl-php/src/Metadata/DefaultMetadataReader.php on line 16

**Comment by stepan-neretin7** [comment]
`<?php
declare(strict_types=1);
 
require __DIR__ . '/vendor/autoload.php';
 
use Symfony\Component\Process\Process;
use YoutubeDl\Options;
use \Done\Subtitles\Subtitles;
use YoutubeDl\Process\ProcessBuilderInterface;
use YoutubeDl\YoutubeDl;
 
function get_files($dir){
    return array_diff(scandir($dir), array('.', '..'));
}
 
 
$yt = new YoutubeDl();
$yt->setBinPath("/usr/local/bin/youtube-dl");
$collection = $yt->download(
    Options::create()
        ->downloadPath('data')
        ->url('https://www.youtube.com/watch?v=aZPis50uvF4')->allSubs(true)->skipDownload(true)->writeSub(true)
 
);
 
var_dump($yt->debug(true));
$files = get_files("data");
if(empty($files)){
    echo "Не удается найти субтитры!";
    exit();
}
 `

**Comment by stepan-neretin7** [comment]
[Code](https://paste.centos.org/view/da30d845)

**Comment by stepan-neretin7** [comment]
Only error wher run in web(by browser)
if i run php filename.php all ok

**Comment by norkunas** [comment]
Could you try to use absolute path for defining downloadPath?

**Comment by stepan-neretin7** [comment]
> Could you try to use absolute path for defining downloadPath?

Yes https://paste.centos.org/view/ed7ecfa4
http://84.38.181.193/

**Comment by norkunas** [comment]
Not sure then, you should probably enable output debugging to see what `youtube-dl` binary outputs and why the metadata is not stored.

**Comment by stepan-neretin7** [comment]
> Not sure then, you should probably enable output debugging to see what `youtube-dl` binary outputs and why the metadata is not stored.

How do I enable it? Even wildly dumb

**Comment by norkunas** [comment]
```php
$yt->debug(function ($type, $buffer) {
  if ($type === Process::ERR) {
        echo 'ERR > '.$buffer.PHP_EOL;
    } else {
        echo 'OUT > '.$buffer.PHP_EOL;
    }
});
```

**Comment by stepan-neretin7** [comment]
> ```
> $yt->debug(function ($type, $buffer) {
>   if ($type === Process::ERR) {
>         echo 'ERR > '.$buffer.PHP_EOL;
>     } else {
>         echo 'OUT > '.$buffer.PHP_EOL;
>     }
> });
> ```

ERR > WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this. OUT > [youtube] aZPis50uvF4: Downloading webpage OUT > [info] Writing video subtitles to: /usr/share/nginx/html/data/_-aZPis50uvF4.ru.vtt OUT > [info] Writing video description metadata as JSON to: /usr/share/nginx/html/data/_-aZPis50uvF4.info.json ERR > WARNING: Unable to download subtitle for "ru": [Errno 13] Permission denied: '/usr/share/nginx/html/data/_-aZPis50uvF4.ru.vtt' ERROR: Cannot write metadata to JSON file /usr/share/nginx/html/data/_-aZPis50uvF4.info.json

**Comment by stepan-neretin7** [comment]
all folder and files in usr/share/nginx/html/ are 777 type

**Comment by norkunas** [comment]
I'm not very familiar with unix permission problems, so will leave it that to you :)

**Comment by stepan-neretin7** [comment]
It's all settled, thanks
