### ISSUE TITLE
Add yt-dlp support

### ISSUE THREAD

**Issue by Write** [norkunas/youtube-dl-php#162]
I currently tried to change binary path to yt-dlp, it seems to download the video correctly, the "only" problem I found for now is `$collection = $yt->download($options);` being empty even if the download is successful

Now, i'm not saying it's easy to fix, but I tought I just might ask as yt-dlp fix issues I had for so many websites that I had with youtube-dl so if support for yt-dlp *is* possible and not too complexe, that would be awesome !

Thanks

**Comment by norkunas** [comment]
> I might do a PR

Feel free :) I'm not against it.

**Comment by norkunas** [comment]
By the way I've just installed yt-dlp to test with at least demo code from readme and it works for me, so for proper debugging I'd need URL's that doesn't work.

**Comment by Mrlaminat** [comment]
Hey Guys, awesome project. I also found some issues with collections and yt-dlp.
First, let me explain what I'm trying to achieve - Get a playlist of videos, without downloading to review them (for example calculated like\dislike proportion and so on). Option --skip-download  is working well.
But looks like code that reading buffer not adding all videos to the collection, only the last one. 

https://github.com/norkunas/youtube-dl-php/blob/615f0c1240a3e3d464e994d2f96f7f58e27de022/src/YoutubeDl.php#L121

And here is line that adding only single(last video to collection) 

https://github.com/norkunas/youtube-dl-php/blob/615f0c1240a3e3d464e994d2f96f7f58e27de022/src/YoutubeDl.php#L149

Maybe I just don't understand something, but anyway let me know what do you think.
Thanks

**Comment by norkunas** [comment]
Hi @Mrlaminat could you give a link to playlist you are trying to download? For me it works as expected :)

**Comment by norkunas** [comment]
I've released new version, could you guys test it if `yt-dlp` works for you properly? :)

**Comment by Mrlaminat** [comment]
@norkunas Thank you for your fast reply. 
I want to use this lib for different purposes, but here you can check with YT links. Tried both, and empty collections in both cases. Actually, I also tried with youtube-dl, and got the same results. I assume that maybe I'm using it in the wrong way. 
```
Options::create()
                ->downloadPath($temporaryStorage)
                ->url('https://www.youtube.com/watch?v=VP195PgSyvw&list=PLxz6_qhdtqWW929SMwKOfqgKaDAXfLqga&index=1')
                ->skipDownload(true)
```
https://www.youtube.com/watch?v=VP195PgSyvw&list=PLxz6_qhdtqWW929SMwKOfqgKaDAXfLqga&index=1
https://www.youtube.com/playlist?list=PLxz6_qhdtqWW929SMwKOfqgKaDAXfLqga

Tried with "orange" youtube as well. Response from it is quite different for the regular youtube. The first buffer output is "% Downloading pc webpage %", and the second is "% Downloading m3u8 information %"

Not sure is it possible to use this lib for different sources.

**Comment by Mrlaminat** [comment]
> You mean you just want to retrieve all video objects without actually downloading them and that's all?

Yes, I'm testing this feature and thinking is it possible or not. Fetch the list of videos with its meta, do business logic, download only necessary videos, and maybe with some delay(queue system). 
Direct downloading works really well :)

**Comment by norkunas** [comment]
Ok so the problem was that if download is skipped then the end file could not be set to metadata. Could you check if https://github.com/norkunas/youtube-dl-php/commit/99c2210db4d27bda6615f1453ae3a0d12d76b488 works for you?

**Comment by Mrlaminat** [comment]
@norkunas Thank you for the fix.
Working well with youtube, get the whole playlist in the collection. 
First I have to mention, maybe not for @norkunas , but for others. Don't use xDebug for debugging. The process is async inside the pipe, and when you debug it slowly, it's saving only the last item from the pipe.
The second is preg_match is not perfect in the case of another source. Let me prepare some fix in next hours. @norkunas If you want I can contact you separately. 
Thank you!

**Comment by norkunas** [comment]
Contributions are very welcome :)

**Comment by Mrlaminat** [comment]
@norkunas Please check https://github.com/norkunas/youtube-dl-php/pull/174. 
Not sure about solutions with the second string, maybe you can find something more "suitable" for you. 
The second change is unsettling $currentVideo, as far as it's using each time the same video settings, and adding it as a new video to my collection. Checked with Youtube looks fine.

**Comment by MichaelBelgium** [comment]
I have a problem where `getVideos()` is empty when using yt-dlp, is anyone having this too?

**Comment by norkunas** [comment]
@MichaelBelgium could you please run in debug mode and print the output that the `yt-dlp` binary responds to you?

**Comment by MichaelBelgium** [comment]
> @MichaelBelgium could you please run in debug mode and print the output that the `yt-dlp` binary responds to you?

Ok so using this code:
```PHP
$dl = new YoutubeDl();
$dl->debug(function ($type, $buffer) {
    echo "$type: $buffer";
});

//use yt-dlp if it's installed on the system, faster downloads and lot more improvements than youtube-dl
$ytdlp = (new ExecutableFinder())->find('yt-dlp');
if($ytdlp !== null)
    $dl->setBinPath($ytdlp);

$video = $dl->download($options)->getVideos()[0];

var_dump($video->getFile());
die();
```

Output:
```
out: [youtube] _VeNOH9i06I: Downloading webpage
out: [youtube] _VeNOH9i06I: Downloading android player API JSON
out: [info] _VeNOH9i06I: Downloading 1 format(s): 251
out: [info] Writing video metadata as JSON to: download/_VeNOH9i06I.info.json
out: [download] Destination: download/_VeNOH9i06I.webm
out: 
[download]   0.0% of 2.39MiB at 181.65KiB/s ETA 00:13out: 
[download]   0.1% of 2.39MiB at 518.41KiB/s ETA 00:04out: 
[download]   0.3% of 2.39MiB at  1.15MiB/s ETA 00:02 out: 
[download]   0.6% of 2.39MiB at  2.40MiB/s ETA 00:00out: 
[download]   1.3% of 2.39MiB at 855.67KiB/s ETA 00:02out: 
[download]   2.6% of 2.39MiB at  1.03MiB/s ETA 00:02 out: 
[download]   5.2% of 2.39MiB at  1.35MiB/s ETA 00:01out: 
[download]  10.4% of 2.39MiB at  2.01MiB/s ETA 00:01out: 
[download]  20.9% of 2.39MiB at  2.70MiB/s ETA 00:00out: 
[download]  41.8% of 2.39MiB at  2.63MiB/s ETA 00:00out: 
[download]  83.6% of 2.39MiB at  3.68MiB/s ETA 00:00out: 
[download] 100% of 2.39MiB at  3.56MiB/s ETA 00:00  out: 
[download] 100% of 2.39MiB in 00:00               out: 
out: [ExtractAudio] Destination: download/_VeNOH9i06I.mp3
out: Deleting original file download/_VeNOH9i06I.webm (pass -k to keep)
```
```
object(SplFileInfo)#12 (2) {
  ["pathName":"SplFileInfo":private]=>
  string(25) "download/_VeNOH9i06I.webm"
  ["fileName":"SplFileInfo":private]=>
  string(16) "_VeNOH9i06I.webm"
}
```

**Comment by norkunas** [comment]
Ok so `yt-dlp` outputs as `[ExtractAudio] Destination:` instead of `[download] Destination:`.
Would you like to contribute and fix this?

**Comment by MichaelBelgium** [comment]
> Ok so `yt-dlp` outputs as `[ExtractAudio] Destination:` instead of `[download] Destination:`. Would you like to contribute and fix this?

Sure! I'll try haha
