### ISSUE TITLE
Possibility to add options

### ISSUE THREAD

**Issue by fonclub** [norkunas/youtube-dl-php#165]
Right now, because of **clone $this**, it is not possible to add additional options that fit the conditions. For example, I want to enable authorization only for downloads from YouTube and write this condition:

`$options = Options::create()->downloadPath(config('uploadPath'))->url($url);    `
`                               
if (substr_count($url, "youtube")) {
                $options->authenticate(config('username'), config('password'));
}`

But then all previous options are overwritten and only authorization remains... This is very inconvenient and it's not clear why it's done this way? If you use just $this, everything works fine.

**Comment by norkunas** [comment]
What's the problem using like?:
```
$options = Options::create()->downloadPath(config('uploadPath'))->url($url);
if (substr_count($url, "youtube")) { $options = $options->authenticate(config('username'), config('password')); }
```

**Comment by norkunas** [comment]
The purpose of `clone $this` is exactly - to clone the object with previous values and apply new ones and return new options object, so I'm not sure how are you getting this

**Comment by fonclub** [comment]
> Also please note that I've a little bit modified your sample code, which exactly overrides $options with your new options: before -> `$options->authenticate()` after -> `$options = $options->authenticate()`

That's what it's all about! It works that way, thank you. There's just more code that way than if you don't use **clone**

**Comment by fonclub** [comment]
https://skr.sh/sAvDrcUAgap

**Comment by norkunas** [comment]
That's just immutable design pattern. For example you can define many option presets, and then use ones you need without worrying about that some non controllable code could change them at the runtime

**Comment by fonclub** [comment]
Thank you:)
