### ISSUE TITLE
System can't find Download(?) path

### ISSUE THREAD

**Issue by Ente** [norkunas/youtube-dl-php#168]
So I got the following code:

```php
public function download_video($link, $Gvpath){
            $downloader = new YoutubeDl();
            $downloader->debug(function ($type, $buffer) {
                echo "[$type]: $buffer";
              });
            $downloader->setBinPath("../vendor/norkunas/youtube-dl-php/youtube-dl.exe");
            $collection = $downloader->download(
                Options::create()
                ->downloadPath(__DIR__ . "/videos")
                ->url($link)
            );

            foreach($collection->getVideos() as $video){
                if($video->getError() !== null){
                    die("There was a problem downloading your video: {$video->getError()}.");
                } else {
                    return array([
                       "message" => "Your video '{$video->getTitle()} has been downloaded to the given location!",
                       "status" => 1
                    ]);
                }
            }
        }

```
So it finds the youtube-dl.exe executable, but for some reason it can't find the download path (or at least i think it can't find it, because the debug message does not tell me).

The debug message is the following:

"[err]: Das System kann den angegebenen Pfad nicht finden."
[Translated: The System can't find the path specified.]

I also tried using the absolute path, e.g. "C:/Users/USER/Downloads" or "C:\\Users\\USER\\Downloads".
It just doesn't find it. Any idea?

And yes, the directories are writeable & visible.

**Comment by norkunas** [comment]
Is there any more output in debug?

**Comment by norkunas** [comment]
Maybe it can't find the binary path instead?

**Comment by Ente** [comment]
Thanks for your answer.
1. It's actually the only debug message I get.
2. I already had the binary error and fixed it by placing the exe into a directory and specifying the path.

Do you may havw any other ideas? Or should I try placing the youtube-dl.exe in the root dir? Would this help?

**Comment by norkunas** [comment]
Could you try to set download path to `sys_get_tmp_dir()` to check if something changes?

**Comment by Ente** [comment]
So well, I tried it all on linux again and got it somehow working. Well but now I get 410 GONE http errors, the youtube-dl is on the latest version

**Comment by norkunas** [comment]
Not sure then :) which provider do you use? Looking at https://github.com/ytdl-org/youtube-dl has no releases since june, so maybe some providers has changed something and it doesn't work anymore. There is a community fork https://github.com/yt-dlp/yt-dlp which gets regular releases, maybe you could try it with this library.

**Comment by Ente** [comment]
Thanks :) It worked. The videos are downloading, buuuut... "There was a problem downloading your video: Conversion failed!."

**Comment by norkunas** [comment]
Is there any more debug info?

**Comment by Ente** [comment]
Well, I just copied it out. Here's the full message, but it seems to be more informational:

"[out]: [youtube] clbt12upuaA: Downloading webpage [out]: [youtube] clbt12upuaA: Downloading android player API JSON [out]: [info] clbt12upuaA: Downloading 1 format(s): 248+251 [out]: [info] Writing video metadata as JSON to: /tmp/Mini Raspberry Pi Server With Built In UPS & Stats Display-clbt12upuaA.info.json [out]: [download] Resuming download at byte 79916275 [out]: [download] Destination: /tmp/Mini Raspberry Pi Server With Built In UPS & Stats Display-clbt12upuaA.f248.webm [out]: [download] 70.6% of 107.92MiB at 767.34KiB/s ETA 00:42[out]: [download] 70.6% of 107.92MiB at 1.77MiB/s ETA 00:17 [out]: [download] 70.6% of 107.92MiB at 3.64MiB/s ETA 00:08[out]: [download] 70.6% of 107.92MiB at 2.53MiB/s ETA 00:12[out]: [download] 70.7% of 107.92MiB at 1.44MiB/s ETA 00:21[out]: [download] 70.7% of 107.92MiB at 1.34MiB/s ETA 00:23[out]: [download] 70.7% of 107.92MiB at 2.66MiB/s ETA 00:11[out]: [download] 70.9% of 107.92MiB at 4.16MiB/s ETA 00:07[out]: [download] 71.1% of 107.92MiB at 6.53MiB/s ETA 00:04[out]: [download] 71.5% of 107.92MiB at 9.55MiB/s ETA 00:03[out]: [download] 72.5% of 107.92MiB at 12.31MiB/s ETA 00:02[out]: [download] 74.3% of 107.92MiB at 14.00MiB/s ETA 00:01[out]: [download] 78.0% of 107.92MiB at Unknown speed ETA Unknown[out]: [download] 79.5% of 107.92MiB at Unknown speed ETA Unknown[out]: [download] 79.5% of 107.92MiB at 254.08KiB/s ETA 01:29 [out]: [download] 79.5% of 107.92MiB at 683.00KiB/s ETA 00:33[out]: [download] 79.5% of 107.92MiB at 1.47MiB/s ETA 00:15 [out]: [download] 79.5% of 107.92MiB at 2.98MiB/s ETA 00:07[out]: [download] 79.5% of 107.92MiB at 1.85MiB/s ETA 00:11[out]: [download] 79.5% of 107.92MiB at 2.33MiB/s ETA 00:09[out]: [download] 79.6% of 107.92MiB at 3.16MiB/s ETA 00:06[out]: [download] 79.7% of 107.92MiB at 4.85MiB/s ETA 00:04[out]: [download] 79.9% of 107.92MiB at 7.60MiB/s ETA 00:02[out]: [download] 80.4% of 107.92MiB at 11.90MiB/s ETA 00:01[out]: [download] 81.3% of 107.92MiB at 16.15MiB/s ETA 00:01[out]: [download] 83.2% of 107.92MiB at 18.72MiB/s ETA 00:00[out]: [download] 86.9% of 107.92MiB at 18.12MiB/s ETA 00:00[out]: [download] 88.6% of 107.92MiB at 14.98MiB/s ETA 00:00[out]: [download] 88.6% of 107.92MiB at 213.90KiB/s ETA 00:59[out]: [download] 88.6% of 107.92MiB at 215.83KiB/s ETA 00:58[out]: [download] 88.6% of 107.92MiB at 494.10KiB/s ETA 00:25[out]: [download] 88.6% of 107.92MiB at 1.02MiB/s ETA 00:12 [out]: [download] 88.6% of 107.92MiB at 1.66MiB/s ETA 00:07[out]: [download] 88.6% of 107.92MiB at 2.19MiB/s ETA 00:05[out]: [download] 88.7% of 107.92MiB at 3.06MiB/s ETA 00:03[out]: [download] 88.8% of 107.92MiB at 4.66MiB/s ETA 00:02[out]: [download] 89.0% of 107.92MiB at 6.33MiB/s ETA 00:01[out]: [download] 89.5% of 107.92MiB at 9.66MiB/s ETA 00:01[out]: [download] 90.4% of 107.92MiB at 12.44MiB/s ETA 00:00[out]: [download] 92.3% of 107.92MiB at 14.16MiB/s ETA 00:00[out]: [download] 96.0% of 107.92MiB at 12.52MiB/s ETA 00:00[out]: [download] 97.4% of 107.92MiB at 13.09MiB/s ETA 00:00[out]: [download] 97.4% of 107.92MiB at Unknown speed ETA Unknown[out]: [download] 97.4% of 107.92MiB at Unknown speed ETA Unknown[out]: [download] 97.4% of 107.92MiB at Unknown speed ETA Unknown[out]: [download] 97.4% of 107.92MiB at 13.15MiB/s ETA 00:00 [out]: [download] 97.4% of 107.92MiB at 2.03MiB/s ETA 00:01[out]: [download] 97.4% of 107.92MiB at 2.44MiB/s ETA 00:01[out]: [download] 97.5% of 107.92MiB at 3.26MiB/s ETA 00:00[out]: [download] 97.6% of 107.92MiB at 4.93MiB/s ETA 00:00[out]: [download] 97.8% of 107.92MiB at 7.22MiB/s ETA 00:00[out]: [download] 98.3% of 107.92MiB at 8.59MiB/s ETA 00:00[out]: [download] 99.2% of 107.92MiB at 9.76MiB/s ETA 00:00[out]: [download] 100% of 107.92MiB at 10.51MiB/s ETA 00:00 [out]: [download] 100% of 107.92MiB in 00:01 [out]: [out]: [download] Destination: /tmp/Mini Raspberry Pi Server With Built In UPS & Stats Display-clbt12upuaA.f251.webm [out]: [download] 0.0% of 9.63MiB at 148.77KiB/s ETA 01:06[out]: [download] 0.0% of 9.63MiB at 420.85KiB/s ETA 00:23[out]: [download] 0.1% of 9.63MiB at 945.64KiB/s ETA 00:10[out]: [download] 0.2% of 9.63MiB at 1.91MiB/s ETA 00:05 [out]: [download] 0.3% of 9.63MiB at 1.50MiB/s ETA 00:06[out]: [download] 0.6% of 9.63MiB at 1.84MiB/s ETA 00:05[out]: [download] 1.3% of 9.63MiB at 2.70MiB/s ETA 00:03[out]: [download] 2.6% of 9.63MiB at 4.22MiB/s ETA 00:02[out]: [download] 5.2% of 9.63MiB at 6.11MiB/s ETA 00:01[out]: [download] 10.4% of 9.63MiB at 7.98MiB/s ETA 00:01[out]: [download] 20.8% of 9.63MiB at 8.67MiB/s ETA 00:00[out]: [download] 41.5% of 9.63MiB at 10.03MiB/s ETA 00:00[out]: [download] 83.1% of 9.63MiB at 10.61MiB/s ETA 00:00[out]: [download] 100% of 9.63MiB at 11.26MiB/s ETA 00:00 [out]: [download] 100% of 9.63MiB in 00:00 [out]: [out]: [Merger] Merging formats into "/tmp/Mini Raspberry Pi Server With Built In UPS & Stats Display-clbt12upuaA.webm" [err]: ERROR: Conversion failed! There was a problem downloading your video: Conversion failed!."

**Comment by Ente** [comment]
I found out
It was a permission error, which did not allow yt-dlp to write into the directory.
its fixed and thank you.

Issue can be closed.
