### ISSUE TITLE
CreateProcess failed Symfony error

### ISSUE THREAD

**Issue by bumbummen99** [norkunas/youtube-dl-php#17]
Hey,

im currently playing around with this script and i installed it as you instructed. when i try to download a video, i get the following error:
>( ! ) Warning: proc_open(): CreateProcess failed, error code - 267 in C:\xampp\htdocs\test\core\lib\vendor\symfony\process\Process.php on line 293

My code to call the script is this one:

    private function videoDownloader($url){
        $dl = new YoutubeDl([
            'extract-audio' => true,
            'audio-format' => 'mp3',
            'audio-quality' => 0, // best
            'output' => '%(title)s.%(ext)s',
        ]);
        $dl->setDownloadPath('/data/');

        $video = $dl->download($url);
        
        return $video;       
    }

I can access youtube-dl over cmd so its path-settings should be fine.

**Comment by norkunas** [comment]
Hello @bumbummen99,

There is a question in stackoverflow about it: http://stackoverflow.com/questions/30296288/php-warning-proc-open-createprocess-failed-error-code-267, please check your download path :)

**Comment by bumbummen99** [comment]
Found the issue myself but Thanks anyway, it's Working now.
________________________________
Von: Tomas<mailto:notifications@github.com>
Gesendet: ‎18.‎01.‎2016 16:49
An: norkunas/youtube-dl-php<mailto:youtube-dl-php@noreply.github.com>
Cc: bumbummen99<mailto:phenninger@web.de>
Betreff: Re: [youtube-dl-php] CreateProcess failed Symfony error (#17)

Hello @bumbummen99,

There is a question in stackoverflow about it: http://stackoverflow.com/questions/30296288/php-warning-proc-open-createprocess-failed-error-code-267, please check your download path :)

---

**Comment by norkunas** [comment]
@bumbummen99 good to know ;)

**Comment by Nasdav** [comment]
@bumbummen99 , I've had the same issue. It would be nice if you share your solution
