### ISSUE TITLE
vendor/autoload.php error

### ISSUE THREAD

**Issue by volkanguzel** [norkunas/youtube-dl-php#18]
Hi, 
I did the setup : composer require norkunas/youtube-dl-php install and 
File patch : /home/username/vendor/norkunas/youtube-dl-php

I'm getting this error
error code : require(/opt/lampp/htdocs/example/youtube/1../vendor/autoload.php): failed to open stream: Böyle bir dosya ya da dizin yok in /opt/lampp/htdocs/example/youtube/1/index2.php on line 2

**Comment by norkunas** [comment]
Hello @volkanguzel,

How do you include the autoload.php file? I think the problem will be that you missed a "/" before the ```../vendor```.

**Comment by volkanguzel** [comment]
autoload.php file location /home/username/vendor/autoload.php

when I copy this file to their local directory can fix my problem ?

**Comment by norkunas** [comment]
I don't understand why you install vendors to the /home/username/ when your www root is in /opt/lampp/htdocs ? You should install it in your project root.

**Comment by volkanguzel** [comment]
when i write this code "composer require norkunas/youtube-dl-php" it upload is here "/home/username/vendor/"

when i write this code "composer require /opt/lampp/htdocs/example/youtube-dl/youtube-dl.php " composer exception error "  [InvalidArgumentException]                                                                       
  Could not find package /opt/lampp/htdocs/example/youtube-dl/youtube-dl.php at any version for y  
  our minimum-stability (stable). Check the package spelling or your minimum-stability  "

**Comment by norkunas** [comment]
As i understand you store your project in /opt/lampp/htdocs/example, so you need to run the ```composer require``` in that path:
```unix
cd /opt/lampp/htdocs/example/youtube/1
composer require norkunas/youtube-dl-php
```
then in your ```/opt/lampp/htdocs/example/youtube/1/index2.php``` file include the autoloader:
```php
require __DIR__ . '/../vendor/autoload.php';
```

**Comment by volkanguzel** [comment]
Thank you, a question

`<?php
require __DIR__ . '/vendor/autoload.php';

use YoutubeDl\YoutubeDl;
use YoutubeDl\Exception\CopyrightException;
use YoutubeDl\Exception\NotFoundException;
use YoutubeDl\Exception\PrivateVideoException;

$dl = new YoutubeDl([
    'continue' => true, // force resume of partially downloaded files. By default, youtube-dl will resume downloads if possible.
    'format' => 'bestvideo',
]);
// For more options go to https://github.com/rg3/youtube-dl#user-content-options

$dl->setDownloadPath('/home/user/downloads');
// Enable debugging
/*$dl->debug(function ($type, $buffer) {
    if (\Symfony\Component\Process\Process::ERR === $type) {
        echo 'ERR > ' . $buffer;
    } else {
        echo 'OUT > ' . $buffer;
    }
});*/
try {
    $video = $dl->download('https://www.youtube.com/watch?v=oDAw7vW7H0c');
    echo $video->getTitle(); // Will return Phonebloks
    // $dl->getFile(); // \SplFileInfo instance of downloaded file
} catch (NotFoundException $e) {
    // Video not found
} catch (PrivateVideoException $e) {
    // Video is private
} catch (CopyrightException $e) {
    // The YouTube account associated with this video has been terminated due to multiple third-party notifications of copyright infringement
} catch (\Exception $e) {
    // Failed to download
}`

the download process is not happening, blank page is coming

**Comment by norkunas** [comment]
Enable debugging or add some logging in try catch statements to check if there are some exceptions

**Comment by volkanguzel** [comment]
Ok enable debugging

ERR > Traceback (most recent call last): File "/usr/bin/youtube-dl", line 3, in import youtube_dl File "/usr/lib/python2.7/dist-packages/youtube_dl/__init__.py", line 15, in from .options import ( File "/usr/lib/python2.7/dist-packages/youtube_dl/options.py", line 7, in from .downloader.external import list_external_downloaders File "/usr/lib/python2.7/dist-packages/youtube_dl/downloader/__init__.py", line 3, in from .common import FileDownloader File "/usr/lib/python2.7/dist-packages/youtube_dl/downloader/common.py", line 8, in from ..utils import ( File "/usr/lib/python2.7/dist-packages/youtube_dl/utils.py", line 27, in import ssl File "/usr/lib/python2.7/ssl.py", line 97, in import _ssl # if we can't import it, let the error propagate ImportError: /opt/lampp/lib/libssl.so.1.0.0: version `OPENSSL_1.0.1' not found (required by /usr/lib/python2.7/lib-dynload/_ssl.x86_64-linux-gnu.so)

**Comment by norkunas** [comment]
```OPENSSL_1.0.1' not found (required by /usr/lib/python2.7/lib-dynload/_ssl.x86_64-linux-gnu.so)``` openssl library needs to be installed, i can't help further from here

**Comment by volkanguzel** [comment]
@norkunas , Thank you for your help.

**Comment by norkunas** [comment]
@volkanguzel no problem.
