### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by IamComing3** [norkunas/youtube-dl-php#189]
During downloading, the prompt file does not exist

```
          $yt = new \YoutubeDl\YoutubeDl();

      
          $options = \YoutubeDl\Options::create()
              ->output(md5($youtube_video->id . '.mp4'))
              ->downloadPath(storage_path('app/public/' . $download_path))
              ->url($video_path);

          $collection = $yt->download($options);

          foreach ($collection->getVideos() as $video) {
              if ($video->getError() !== null) {
                  // Error downloading video:{$video->getError()}";
              } else {
                 // $video->getFile(); // \SplFileInfo instance of downloaded file
              }
          }
```

The download starts normally,
![image](https://user-images.githubusercontent.com/16791768/205024709-77e99069-9015-4feb-bac9-3c7e75daa466.png)

Each time  274bbf218f5e52f23a9ddb47d9dd7adb.f140.part downloaded to 7.7M，the prompt file does not exist

![image](https://user-images.githubusercontent.com/16791768/205025495-6da9754c-24b4-4022-b98b-3f2c7b6c3d8e.png)

![image](https://user-images.githubusercontent.com/16791768/205025546-7c197946-cb7f-4b2d-9a2f-62060320a097.png)

**Comment by norkunas** [comment]
:man_shrugging: i guess that error comes from the binary itself so I don't think that the problem lies in this library.

can you give me the url you try to download, so i can test it locally?

**Comment by IamComing3** [comment]
the video url [https://www.youtube.com/watch?v=uSFnEOK376k&t=1s](https://www.youtube.com/watch?v=uSFnEOK376k&t=1s) ,thanks a lot

**Comment by norkunas** [comment]
I've tested it and it works for me.

<details>
<summary>
here is the output
</summary>
[youtube] uSFnEOK376k: Downloading webpage
[youtube] uSFnEOK376k: Downloading android player API JSON
[info] uSFnEOK376k: Downloading 1 format(s): 248+251
[info] Writing video metadata as JSON to: /youtube-dl-php/dd/F-35B – World's Most Modern & Insane Stealth Fighter Jet-uSFnEOK376k.info.json
[download] Destination: /youtube-dl-php/dd/F-35B – World's Most Modern & Insane Stealth Fighter Jet-uSFnEOK376k.f248.webm

[download]   0.0% of   63.85MiB at  503.16KiB/s ETA 02:10
[download]   0.0% of   63.85MiB at    1.27MiB/s ETA 00:50
[download]   0.0% of   63.85MiB at    2.33MiB/s ETA 00:27
[download]   0.0% of   63.85MiB at    4.64MiB/s ETA 00:13
[download]   0.0% of   63.85MiB at    4.45MiB/s ETA 00:14
[download]   0.1% of   63.85MiB at    5.48MiB/s ETA 00:11
[download]   0.2% of   63.85MiB at    7.48MiB/s ETA 00:08
[download]   0.4% of   63.85MiB at   11.05MiB/s ETA 00:05
[download]   0.8% of   63.85MiB at   16.28MiB/s ETA 00:03
[download]   1.6% of   63.85MiB at   23.33MiB/s ETA 00:02
[download]   3.1% of   63.85MiB at   32.17MiB/s ETA 00:01
[download]   6.3% of   63.85MiB at   32.74MiB/s ETA 00:01
[download]  12.5% of   63.85MiB at   40.75MiB/s ETA 00:01
[download]  15.5% of   63.85MiB at   42.86MiB/s ETA 00:01
[download]  15.5% of   63.85MiB at  616.81KiB/s ETA 01:30
[download]  15.5% of   63.85MiB at    1.52MiB/s ETA 00:35
[download]  15.5% of   63.85MiB at    3.12MiB/s ETA 00:17
[download]  15.5% of   63.85MiB at    5.92MiB/s ETA 00:09
[download]  15.6% of   63.85MiB at    3.92MiB/s ETA 00:13
[download]  15.6% of   63.85MiB at    4.62MiB/s ETA 00:11
[download]  15.7% of   63.85MiB at    5.66MiB/s ETA 00:09
[download]  15.9% of   63.85MiB at    8.48MiB/s ETA 00:06
[download]  16.3% of   63.85MiB at   12.92MiB/s ETA 00:04
[download]  17.1% of   63.85MiB at   17.17MiB/s ETA 00:03
[download]  18.6% of   63.85MiB at   25.84MiB/s ETA 00:02
[download]  21.8% of   63.85MiB at   34.50MiB/s ETA 00:01
[download]  28.0% of   63.85MiB at   41.41MiB/s ETA 00:01
[download]  30.4% of   63.85MiB at   42.50MiB/s ETA 00:01
[download]  30.4% of   63.85MiB at  867.13KiB/s ETA 00:52
[download]  30.4% of   63.85MiB at    1.97MiB/s ETA 00:22
[download]  30.4% of   63.85MiB at    3.90MiB/s ETA 00:11
[download]  30.4% of   63.85MiB at    7.28MiB/s ETA 00:06
[download]  30.5% of   63.85MiB at    4.14MiB/s ETA 00:10
[download]  30.5% of   63.85MiB at    5.47MiB/s ETA 00:08
[download]  30.6% of   63.85MiB at    6.83MiB/s ETA 00:06
[download]  30.8% of   63.85MiB at   10.38MiB/s ETA 00:04
[download]  31.2% of   63.85MiB at   15.18MiB/s ETA 00:02
[download]  32.0% of   63.85MiB at   22.75MiB/s ETA 00:01
[download]  33.5% of   63.85MiB at   30.24MiB/s ETA 00:01
[download]  36.7% of   63.85MiB at   23.46MiB/s ETA 00:01
[download]  42.9% of   63.85MiB at   31.33MiB/s ETA 00:01
[download]  45.8% of   63.85MiB at   33.77MiB/s ETA 00:01
[download]  45.8% of   63.85MiB at  815.38KiB/s ETA 00:43
[download]  45.8% of   63.85MiB at    1.77MiB/s ETA 00:19
[download]  45.8% of   63.85MiB at    3.50MiB/s ETA 00:09
[download]  45.8% of   63.85MiB at    6.63MiB/s ETA 00:05
[download]  45.8% of   63.85MiB at    5.64MiB/s ETA 00:06
[download]  45.9% of   63.85MiB at    6.05MiB/s ETA 00:05
[download]  46.0% of   63.85MiB at    8.41MiB/s ETA 00:04
[download]  46.2% of   63.85MiB at   11.80MiB/s ETA 00:02
[download]  46.5% of   63.85MiB at   18.33MiB/s ETA 00:01
[download]  47.3% of   63.85MiB at   23.09MiB/s ETA 00:01
[download]  48.9% of   63.85MiB at   31.83MiB/s ETA 00:01
[download]  52.0% of   63.85MiB at   34.17MiB/s ETA 00:00
[download]  58.3% of   63.85MiB at    1.73MiB/s ETA 00:15
[download]  60.9% of   63.85MiB at    2.08MiB/s ETA 00:12
[download]  60.9% of   63.85MiB at  Unknown B/s ETA Unknown
[download]  60.9% of   63.85MiB at  Unknown B/s ETA 00:08  
[download]  60.9% of   63.85MiB at    5.15MiB/s ETA 00:04
[download]  60.9% of   63.85MiB at    9.13MiB/s ETA 00:02
[download]  61.0% of   63.85MiB at    4.45MiB/s ETA 00:05
[download]  61.0% of   63.85MiB at    5.34MiB/s ETA 00:04
[download]  61.1% of   63.85MiB at    7.39MiB/s ETA 00:03
[download]  61.3% of   63.85MiB at   11.08MiB/s ETA 00:02
[download]  61.7% of   63.85MiB at   15.65MiB/s ETA 00:01
[download]  62.5% of   63.85MiB at   22.86MiB/s ETA 00:01
[download]  64.1% of   63.85MiB at   30.85MiB/s ETA 00:00
[download]  67.2% of   63.85MiB at   38.38MiB/s ETA 00:00
[download]  73.4% of   63.85MiB at   43.90MiB/s ETA 00:00
[download]  76.0% of   63.85MiB at   44.49MiB/s ETA 00:00
[download]  76.0% of   63.85MiB at  606.46KiB/s ETA 00:26
[download]  76.0% of   63.85MiB at    1.49MiB/s ETA 00:10
[download]  76.1% of   63.85MiB at    3.18MiB/s ETA 00:04
[download]  76.1% of   63.85MiB at    6.27MiB/s ETA 00:02
[download]  76.1% of   63.85MiB at    3.75MiB/s ETA 00:04
[download]  76.1% of   63.85MiB at    5.08MiB/s ETA 00:03
[download]  76.2% of   63.85MiB at    6.44MiB/s ETA 00:02
[download]  76.4% of   63.85MiB at    9.78MiB/s ETA 00:01
[download]  76.8% of   63.85MiB at   14.48MiB/s ETA 00:01
[download]  77.6% of   63.85MiB at   20.83MiB/s ETA 00:00
[download]  79.2% of   63.85MiB at   29.27MiB/s ETA 00:00
[download]  82.3% of   63.85MiB at   35.99MiB/s ETA 00:00
[download]  88.6% of   63.85MiB at   41.38MiB/s ETA 00:00
[download]  91.5% of   63.85MiB at   38.35MiB/s ETA 00:00
[download]  91.5% of   63.85MiB at  574.88KiB/s ETA 00:09
[download]  91.5% of   63.85MiB at    1.50MiB/s ETA 00:03
[download]  91.5% of   63.85MiB at    3.07MiB/s ETA 00:01
[download]  91.5% of   63.85MiB at    5.96MiB/s ETA 00:00
[download]  91.5% of   63.85MiB at    3.94MiB/s ETA 00:01
[download]  91.6% of   63.85MiB at    4.83MiB/s ETA 00:01
[download]  91.7% of   63.85MiB at    6.81MiB/s ETA 00:00
[download]  91.9% of   63.85MiB at   10.07MiB/s ETA 00:00
[download]  92.3% of   63.85MiB at   14.45MiB/s ETA 00:00
[download]  93.1% of   63.85MiB at   21.96MiB/s ETA 00:00
[download]  94.6% of   63.85MiB at   30.19MiB/s ETA 00:00
[download]  97.7% of   63.85MiB at   33.01MiB/s ETA 00:00
[download] 100.0% of   63.85MiB at   36.78MiB/s ETA 00:00
[download] 100% of   63.85MiB in 00:00:06 at 10.26MiB/s  
[download] Destination: /youtube-dl-php/dd/F-35B – World's Most Modern & Insane Stealth Fighter Jet-uSFnEOK376k.f251.webm

[download]   0.0% of    5.95MiB at  684.67KiB/s ETA 00:08
[download]   0.0% of    5.95MiB at    1.65MiB/s ETA 00:03
[download]   0.1% of    5.95MiB at    3.27MiB/s ETA 00:01
[download]   0.2% of    5.95MiB at    6.23MiB/s ETA 00:00
[download]   0.5% of    5.95MiB at    4.42MiB/s ETA 00:01
[download]   1.0% of    5.95MiB at    5.72MiB/s ETA 00:01
[download]   2.1% of    5.95MiB at    7.74MiB/s ETA 00:00
[download]   4.2% of    5.95MiB at   10.88MiB/s ETA 00:00
[download]   8.4% of    5.95MiB at   16.26MiB/s ETA 00:00
[download]  16.8% of    5.95MiB at   22.65MiB/s ETA 00:00
[download]  33.6% of    5.95MiB at   29.57MiB/s ETA 00:00
[download]  67.2% of    5.95MiB at   37.68MiB/s ETA 00:00
[download] 100.0% of    5.95MiB at   40.16MiB/s ETA 00:00
[download] 100% of    5.95MiB in 00:00:00 at 34.39MiB/s  
[Merger] Merging formats into "/youtube-dl-php/dd/F-35B – World's Most Modern & Insane Stealth Fighter Jet-uSFnEOK376k.webm"
Deleting original file /youtube-dl-php/dd/F-35B – World's Most Modern & Insane Stealth Fighter Jet-uSFnEOK376k.f251.webm (pass -k to keep)
Deleting original file /youtube-dl-php/dd/F-35B – World's Most Modern & Insane Stealth Fighter Jet-uSFnEOK376k.f248.webm (pass -k to keep)
</details>
