### ISSUE TITLE
$dl->getFilename() returns ""

### ISSUE THREAD

**Issue by efka-9** [norkunas/youtube-dl-php#19]
Can't get filename of downloaded file. This method only displayes correct string with `'restrict-filenames' => true` option. My options array:          

```
            'extract-audio' => true,
            'audio-format' => 'mp3',
            'audio-quality' => 0, // best
            'output' => '%(title)s.%(ext)s',
            'no-playlist'  => true,
```

**Comment by norkunas** [comment]
@Ratnote is this bug applies only for some of urls or for all?

**Comment by Ratnote** [comment]
Good question. I think it only appears when filename contains special characters (ė, š, "). Try this one - https://www.youtube.com/watch?v=gwlLHYBXszU.

**Comment by norkunas** [comment]
@Ratnote ok, i can reproduce it. Also what OS do you use?

**Comment by Ratnote** [comment]
@norkunas My virtual machine runs on Ubuntu 16.04

**Comment by norkunas** [comment]
Ok, so I've tested with php 7.0 and php 7.1RC1 so it seems that this is an php bug because in later version it works fine for me.
I've tried to use ```setlocale(LC_ALL, "en_US.UTF-8")```, played with utf8 encoding/decoding but none of these worked for me..

**Comment by Ratnote** [comment]
@norkunas What php version do you use? I use 'restrict-filenames', it's not perfect but still it's a solution. Thanks!

**Comment by norkunas** [comment]
Currently I'm using 7.0.9. Glad you resolved that with this option, missed it somehow 👍

**Comment by mtrebles** [comment]
Hi. Is it possible to save file with special chars like "ś", "ą"? Now when I'm trying file is saving without that chars. If I run \\ youtube-dl --extract-audio --audio-format=mp3 uri \\ straight from terminal I'm getting file with this chars but If I'll post URI by your class I don't get this chars.
Regards

**Comment by norkunas** [comment]
@mtrebles it should work since php >7.1

**Comment by mtrebles** [comment]
@norkunas So I've updated php to 7.1.2. File is still saving without special characters. Additionally If downloaded file contains special chars like "ą", "ś", "ć" etc. $video['_filename'] output is empty. (In PHP 5.6 $video['_filename'] was only without special chars)

**Comment by mtrebles** [comment]
@norkunas My mistake. In PHP 5.6 output was also empty (but sometimes was only without special chars). I don't know why this happend.

**Comment by norkunas** [comment]
Can you give me url you test?
