### ISSUE TITLE
postprocessor-args not impplimented

### ISSUE THREAD

**Issue by miapuffia** [norkunas/youtube-dl-php#204]
Hello,

Am I missing something or is there not a function in Options to set post-processor args? I see the variable but no setter. I'd like to use this to set extracted audio metadata and embedded album art.

Thanks

**Comment by miapuffia** [comment]
Also of note is that I'm trying to do it that way so I can set metadata with custom values.

**Comment by norkunas** [comment]
Hello, probably missed. Contribution welcome

**Comment by miapuffia** [comment]
I added it to the file in my composer project and it works just fine, so I'll PR properly when I get a chance. Until then, this was all I added to Options.php:

```
public function postProcessorArgs(?string $postProcessorArgs): self
{
    $new = clone $this;
    $new->postProcessorArgs = $postProcessorArgs;

    return $new;
}
```

and I used it quite easily with `->postProcessorArgs("-metadata title={$title} -metadata artist={$artist} -metadata album={$album}")`

**Comment by miapuffia** [comment]
Submitted the PR
