### ISSUE TITLE
Missing developer option(s)

### ISSUE THREAD

**Issue by MichaelBelgium** [norkunas/youtube-dl-php#212]
I wanna add the option `--allow-u` which is a "developer" option - from yt-dlp (i'm not sure about youtube-dl - but there's no way to set it in the `Options` class, can this be added? Or perhaps a more free way to add raw options, in case the option can't be set.

`--allow-u` means: download/list UNPLAYABLE formats

There are probably more but I only know about that one

**Comment by norkunas** [comment]
Sure, contributions are always welcome :slightly_smiling_face:

**Comment by MichaelBelgium** [comment]
Euh, It's kind of urgent and I don't think you'll find volunteers 😆 You can implement it the quickest

Something like this `->raw()`

```
\YoutubeDl\Options::create()
    ->raw('--allow-u')
    ->noPart(true)
    ->downloadPath('/tmp')
    ->format('bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best[ext=m4a]')
    ->url($uri);
```

**Comment by norkunas** [comment]
If it's really urgent then just implement custom process builder and pass that option :) because I cannot promise that I will do this myself
