### ISSUE TITLE
YoutubeDl\Entity\Video::getTags(): Return value must be of type array, null returned

### ISSUE THREAD

**Issue by 9x3l6** [norkunas/youtube-dl-php#216]
The function returns null sometimes, probably a good idea to handle array or null.

```
524     /**
525      * @return string[]
526      */
527     public function getTags(): array
528     {
529         return $this->get('tags');
530     }
```

**Comment by norkunas** [comment]
Which provider returns this as null? Imho doesn't make sense that it do this,as tags are array,arrays can be empty,why return null? Or this is a case when it doesn't return tags at all and this lib doesn't account for this?

**Comment by 9x3l6** [comment]
I fixed it for you, made it do what the other parts of the code do return a empty array https://github.com/9x3l6/youtube-dl-php/pull/1

**Comment by 9x3l6** [comment]
In regards to your question "Which provider returns this as null?" answer is TikTok

**Comment by norkunas** [comment]
> I fixed it for you, made it do what the other parts of the code do return a empty array [9x3l6#1](https://github.com/9x3l6/youtube-dl-php/pull/1)

So why didn't you open PR against this repo? :slightly_smiling_face:

**Comment by norkunas** [comment]
I've cherry picked your commit in #219
