### ISSUE TITLE
Need `-U`, `--update` option to help with debugging when problems happen

### ISSUE THREAD

**Issue by 9x3l6** [norkunas/youtube-dl-php#217]
Also this option `-U, --update` is required to be used for when submitting issues with `youtube-dl`/`yt-dlp`

```
Provide verbose output that clearly demonstrates the problem
- [] Run your yt-dlp command with -vU flag added (yt-dlp -vU <your command line>)
- [] If using API, add 'verbose': True to YoutubeDL params instead
- [] Copy the WHOLE output (starting with [debug] Command-line config) and insert it below
```

https://github.com/9x3l6/youtube-dl-php/pull/3

Thank you!

**Comment by norkunas** [comment]
I don't think that this tool should run in privileged mode to update itself, you should do that manually or with some cronjob

**Comment by norkunas** [comment]
But what's the point, if you can do that directly? :)
