### ISSUE TITLE
Unable to run basic example with an Access denied error.

### ISSUE THREAD

**Issue by zuinqstudio** [norkunas/youtube-dl-php#234]
Trying the library on macos, the basic example silently fails at `YoutubeDl line 133` , with the buffer containing:

    /usr/local/bin/youtube-dl: line 1: syntax error near unexpected token `newline'
    /usr/local/bin/youtube-dl: line 1: `<h1>Access denied</h1>'

I'm guessing youtube is giving that response, but tried including a user agent header with no success. Any tip pointing in the right direction is much appreciated :) Please find my code below:

    $collection = $yt->download(
        Options::create()
            ->downloadPath('/path/to/downloads')
            ->url('https://www.youtube.com/watch?v=oDAw7vW7H0c')
            ->header("HTTP_USER_AGENT", self::USER_AGENT)
    );

**Comment by zuinqstudio** [comment]
Answering my own question in case someone finds it useful: I ended up downloaded `youtube-dl` from a different repo as suggested [here](https://github.com/ytdl-org/youtube-dl/issues/32647)

**Comment by norkunas** [comment]
https://github.com/yt-dlp/yt-dlp is a bit newer toor and more maintained in case you interested
