### ISSUE TITLE
Mixcloud+mp3 - requested format not available

### ISSUE THREAD

**Issue by csimpi** [norkunas/youtube-dl-php#24]
Hi!

It's me again.
First: thank for your work, it's very cool! :)

Sorry for bother,but i have an another issue: 
It works like a charm with youtube and soundcloud (mp3 and mp4 too), but i get the error below, if i provide a mixcloud url and choose mp3 format.
With mp4 format it works.
Avconv installed

`Failed to download:exception 'Symfony\Component\Process\Exception\ProcessFailedException' with message 'The command "youtube-dl --continue --format bestaudio --extract-audio --audio-format mp3 --audio-quality 0 --output "%(id)s.%(ext)s" --no-playlist --print-json --ignore-config 'https://www.mixcloud.com/MalibuRum/play-1-dj-mks-summer-throwdown-mix'" failed. Exit Code: 1(General error) Working directory: /var/www/converter/public/download Output: ================ Error Output: ================ ERROR: requested format not available ' in /var/www/converter/public/vendor/symfony/process/Process.php:232 Stack trace: #0 /var/www/converter/public/vendor/norkunas/youtube-dl-php/src/YoutubeDl.php(245): Symfony\Component\Process\Process->mustRun(NULL) #1 /var/www/converter/public/index.php(108): YoutubeDl\YoutubeDl->download('https://www.mix...') #2 {main}`

**Comment by norkunas** [comment]
Can you share the url? I will check this later today

**Comment by norkunas** [comment]
@csimpi you shouldn't provide the --format bestaudio format if you trying to extract the audio and not the video
