### ISSUE TITLE
Sign in to confirm you’re not a bot

### ISSUE THREAD

**Issue by berenceylan** [norkunas/youtube-dl-php#242]
I am getting Sign in to confirm you’re not a bot. error. To overcome this i tried to use 

<img width="991" alt="image" src="https://github.com/user-attachments/assets/0e292264-736e-488f-acaf-51497a91f573">

this method. But it doesnt seem to be working.

**Comment by norkunas** [comment]
With which provider?

**Comment by norkunas** [comment]
https://github.com/yt-dlp/yt-dlp/issues/10128
