### ISSUE TITLE
Options for passing PO Token?

### ISSUE THREAD

**Issue by mokhosh** [norkunas/youtube-dl-php#245]
Is there currently a way to implement this?
https://github.com/yt-dlp/yt-dlp/wiki/Extractors

**Comment by norkunas** [comment]
@mokhosh what do you mean implement? is something not working for you? as I read these are manual methods to obtain the PO token

**Comment by norkunas** [comment]
Ok, I see - there was no `extractor-args` option previously

**Comment by norkunas** [comment]
Released as v2.8.0
