### ISSUE TITLE
Symfony 3.2 - ExecutableFinder can't locate binary / setBinPath doesn't include ENV path

### ISSUE THREAD

**Issue by runforrestrun** [norkunas/youtube-dl-php#25]
Maybe I'm overlooking something. It works in some degree.

I'm using  a Symfony 3.2 deployment. I required your code via composer. 

**This works**
I can successfully test the mp3 example WITHOUT specifying the youtube-dl binary path in the root directory. 

symfony-project-folder/
    app/
    vendor/
    test.php
    blabla/

test.php::
```
<?php
require __DIR__ . '/vendor/autoload.php';

use YoutubeDl\YoutubeDl;

$dl = new YoutubeDl([
    'extract-audio' => true,
    'audio-format' => 'mp3',
    'audio-quality' => 0, // best
    'output' => '%(title)s.%(ext)s',
]);
$dl->setDownloadPath('/home/user/downloads');

$video = $dl->download('https://www.youtube.com/watch?v=oDAw7vW7H0c');
```

**This doesn't work**
When I try to use it within my bundle. I have to specify the binary path. 
Strangely the ExecutableFinder doesn't seem to work. So I explicitly do it by setting: `setBinPath('/usr/local/bin/youtube-dl')`
But than this error pops up:

> Error Output:
> ================
> ERROR: ffprobe or avprobe not found. Please install one.

So it seems that the ExecutableFinder can't see my youtube-dl binary and its ENV settings. youtube-dl. ffmpeg, ffprobe, avprobe are all installed onto my system.

 
This is the executed command, when I copy/paste the command into my shell it works fine. `'/usr/local/bin/youtube-dl' 'https://www.youtube.com/watch?v=oDAw7vW7H0c' '--no-playlist' '--print-json' '--ignore-config' '--extract-audio' '--audio-format=mp3' '--audio-quality=0' '--output=%(title)s.%(ext)s'
`

As a temporary solution I cloned your YoutubeDl to YoutubeDlFixed
and added:
```
        $process = $processBuilder->getProcess();
        $process->setEnv(['PATH' => '/Users/forrestgump/.composer/vendor/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/ruby/bin:/usr/local/bin:/Users/forrestgump/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/mysql/bin']);

        try {
            $process->mustRun(is_callable($this->debug) ? $this->debug : null);
        } catch (\Exception $e) {
            throw $this->handleException($e);
        }
```

So my question is: Is this is a bug? or a mistake from my side? Did I overlook something?

**Comment by norkunas** [comment]
@runforrestrun is open_basedir set in your env?

**Comment by runforrestrun** [comment]
From the terminal, php -i | grep -i "basedir" gives:
`open_basedir => no value => no value`

From the Symfony installation:
![screen shot 2016-12-23 at 14 17 48](https://cloud.githubusercontent.com/assets/3511226/21454680/a44e542e-c91a-11e6-8f46-cd6c42ce3382.png)

There was a case with similar symptoms back in 2012: 

> Process builder no longer inherits the current environment:
[https://github.com/symfony/symfony/issues/3555
](https://github.com/symfony/symfony/issues/3555
)
Please bare with me. I'm actually pretty new to the Git game and Github workflows. I 'll try to be as expressive and helpful as possible.

**Comment by norkunas** [comment]
Could you try to test with executable finder standalone if it works as it should be in your environment, also with process builder and process?
