### ISSUE TITLE
--convert-thumbnails ?

### ISSUE THREAD

**Issue by mostafa-norouzi** [norkunas/youtube-dl-php#257]
Hi,

I can see in below link  --convert-thumbnails switch that guess not implemented in this PHP wrapper :
https://github.com/yt-dlp/yt-dlp/blob/master/README.md

Do you have any plan to add it? Or guide me how can I use it?
With the best.

**Comment by norkunas** [comment]
Hi,

Add the new option to `YoutubeDl\Options` class and a test :)

**Comment by mostafa-norouzi** [comment]
But I don't want to manipulate library files. Isn't possible to add custom param through current class?

**Comment by norkunas** [comment]
If you want something to be present someone must contribute the code :) of course you can extend the options class and add it by yourself but then you are on your own :)
