### ISSUE TITLE
ERROR: m3u8 download detected but ffmpeg or avconv could not be found

### ISSUE THREAD

**Issue by joseska** [norkunas/youtube-dl-php#26]
Hi. We have this error when downloading a video from: //config.playwire.com/21772/videos/v2/5298568/zeus.json

ffmpeg is installed an if I use on terminal: " youtube-dl //config.playwire.com/21772/videos/v2/5298568/zeus.json". work perfect....

Thank....

**Comment by norkunas** [comment]
Hi, which library version do you use? Also keep in mind that designed this library to work with single videos and not playlists because its hard to intercept errors when downloading multiple videos at once

**Comment by joseska** [comment]
Hi..... This library version: 
"norkunas/youtube-dl-php": "^0.3.0",

thanks....

**Comment by joseska** [comment]
hi.... With this option enable: 
'ffmpeg-location' => '/usr/local/bin/ffmpeg',
'prefer-ffmpeg' => true,
----------------------------------

Fatal error: Uncaught exception 'Symfony\Component\OptionsResolver\Exception\InvalidOptionsException' with message 'The option "ffmpeg-location" with value "/usr/local/bin/ffmpeg" is invalid.' in /var/www/html/vendor/symfony/options-resolver/OptionsResolver.php:862 Stack trace: #0 /var/www/html/vendor/symfony/options-resolver/OptionsResolver.php(716): Symfony\Component\OptionsResolver\OptionsResolver->offsetGet('ffmpeg-location') #1 /var/www/html/vendor/norkunas/youtube-dl-php/src/YoutubeDl.php(68): Symfony\Component\OptionsResolver\OptionsResolver->resolve(Array) #2 /var/www/html/1_deportes_highlights.php(23): YoutubeDl\YoutubeDl->__construct(Array) #3 {main} thrown in /var/www/html/vendor/symfony/options-resolver/OptionsResolver.php on line 862




-------------------------------------------------------------
with this option:
// 'ffmpeg-location' => '/usr/local/bin/ffmpeg', #disable this......
'prefer-ffmpeg' => true,
------------------------
exception 'Symfony\Component\Process\Exception\ProcessFailedException' with message 'The command "/usr/local/bin/youtube-dl --continue --format best[ext=mp4] --output "%(title)s.%(ext)s" --restrict-filenames --download-archive registro_deportes_highlights.txt --prefer-ffmpeg --no-playlist --print-json --ignore-config '//config.playwire.com/14907/videos/v2/5299851/zeus.json'" failed. Exit Code: 1(General error) Working directory: /var/www/html/download Output: ================ {"display_id": "5299851", "extractor": "Playwire", "protocol": "m3u8", "fps": null, "format": "hls-1527 - 854x480", "requested_subtitles": null, "tbr": 1527, "height": 480, "_filename": "TOR_V_MIL_Extended.mp4", "preference": null, "duration": 501.32, "manifest_url": "https://cdn.video.playwire.com/21772/videos/5299851/video-sd.m3u8", "format_id": "hls-1527", "playlist_index": null, "playlist": null, "thumbnails": [{"url": "https://cdn.video.playwire.com/21772/videos/5299851/poster_0000.png", "id": "0"}], "title": "TOR V MIL Extended", "url": "https://cdn.video.playwire.com/21772/videos/5299851/video-sd.m3u8", "extractor_key": "Playwire", "vcodec": "avc1.77.30", "http_headers": {"Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Language": "en-us,en;q=0.5", "Accept-Encoding": "gzip, deflate", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)"}, "id": "5299851", "width": 854, "ext": "mp4", "webpage_url": "https://config.playwire.com/14907/videos/v2/5299851/zeus.json", "formats": [{"http_headers": {"Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Language": "en-us,en;q=0.5", "Accept-Encoding": "gzip, deflate", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)"}, "protocol": "m3u8", "format": "hls-meta - multiple (Quality selection URL)", "url": "https://config.playwire.com/14907/videos/v2/5299851/abr-non-hd.m3u8", "quality": 1, "format_note": "Quality selection URL", "ext": "mp4", "preference": -100, "format_id": "hls-meta", "resolution": "multiple"}, {"protocol": "https", "format": "1000 - 480x270", "tbr": 1000, "height": 270, "preference": null, "manifest_url": "https://cdn.video.playwire.com/21772/videos/5299851/video-mobile.mp4", "format_id": "1000", "http_headers": {"Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Language": "en-us,en;q=0.5", "Accept-Encoding": "gzip, deflate", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)"}, "url": "https://cdn.video.playwire.com/21772/videos/5299851/video-mobile.mp4", "vcodec": null, "width": 480, "ext": "mp4"}, {"protocol": "https", "format": "1200 - 854x480", "tbr": 1200, "height": 480, "preference": null, "manifest_url": "https://cdn.video.playwire.com/21772/videos/5299851/video-sd.mp4", "format_id": "1200", "http_headers": {"Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Language": "en-us,en;q=0.5", "Accept-Encoding": "gzip, deflate", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)"}, "url": "https://cdn.video.playwire.com/21772/videos/5299851/video-sd.mp4", "vcodec": null, "width": 854, "ext": "mp4"}, {"http_headers": {"Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Language": "en-us,en;q=0.5", "Accept-Encoding": "gzip, deflate", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)"}, "protocol": "m3u8", "format": "hls-1297 - 480x270", "url": "https://cdn.video.playwire.com/21772/videos/5299851/video-mobile.m3u8", "vcodec": "avc1.77.30", "tbr": 1297, "height": 270, "width": 480, "ext": "mp4", "preference": null, "fps": null, "manifest_url": "https://cdn.video.playwire.com/21772/videos/5299851/video-mobile.m3u8", "format_id": "hls-1297", "acodec": "mp4a.40.2"}, {"http_headers": {"Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7", "Accept-Language": "en-us,en;q=0.5", "Accept-Encoding": "gzip, deflate", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)"}, "protocol": "m3u8", "format": "hls-1527 - 854x480", "url": "https://cdn.video.playwire.com/21772/videos/5299851/video-sd.m3u8", "vcodec": "avc1.77.30", "tbr": 1527, "height": 480, "width": 854, "ext": "mp4", "preference": null, "fps": null, "manifest_url": "https://cdn.video.playwire.com/21772/videos/5299851/video-sd.m3u8", "format_id": "hls-1527", "acodec": "mp4a.40.2"}], "fulltitle": "TOR V MIL Extended", "thumbnail": "https://cdn.video.playwire.com/21772/videos/5299851/poster_0000.png", "webpage_url_basename": "zeus.json", "acodec": "mp4a.40.2"} Error Output: ================ ERROR: m3u8 download detected but ffmpeg or avconv could not be found. Please install one. ' in /var/www/html/vendor/symfony/process/Process.php:233 Stack trace: #0 /var/www/html/vendor/norkunas/youtube-dl-php/src/YoutubeDl.php(245): Symfony\Component\Process\Process->mustRun(NULL) #1 /var/www/html/1_deportes_highlights.php(64): YoutubeDl\YoutubeDl->download('//config.playwi...') #2 {main}

**Comment by norkunas** [comment]
@joseska are you sure that `/usr/local/bin/ffmpeg` exists? Because options resolver validates it and throws exception if it is not a file and if it is not a directory

**Comment by joseska** [comment]
Hi..... sorry. the problem was that I install ffmpeg on /root/bin/ and in this location have an permission error.

Now I re-Install ffmpeg on /usr/local/bin and with "'ffmpeg-location' => '/usr/local/bin/ffmpeg'," work Perfect.....

thanks for your support.......

**Comment by norkunas** [comment]
I'm glad you solved it :)

**Comment by Mitul1995** [comment]
How can we fix this issue for windows?

**Comment by norkunas** [comment]
Did you check if ffmpeg/avconv is actually reachable via php? Where do you store your yt binary? How do you configure the path to it or ffmpeg/avconv?

**Comment by norkunas** [comment]
Converting to audio ffmpeg or avconv is required as stated in README. So you need to [download it](https://www.ffmpeg.org/download.html), store it somewhere and configure library to point to ffmpeg/avconv binary.
