### ISSUE TITLE
download-archive error

### ISSUE THREAD

**Issue by joseska** [norkunas/youtube-dl-php#27]
Hi. One question. I use 'download-archive' for non download the same video again.

the problem is when the video was download before, the "$video->getFilename();" break my foreach.

I need:
if (video was downloaded before) {
continue;
}
sorry for my english.
Thanks.....

**Comment by norkunas** [comment]
Hi, i've never tested this option so i didn't know that if this option is set then the response wouldn't contain json, so in this case `YoutubeDl\Entity\Video` can't be properly populated. So this option should be disabled.
I just suggest you to use some other caching mechanism. If you want please submit a PR disabling this option.
