### ISSUE TITLE
getFilesize not work in other format

### ISSUE THREAD

**Issue by mohaphez** [norkunas/youtube-dl-php#29]
hi man ! 
thanks for your package 
i use getFilesize() for get downloaded file size but this option worked in 'bestvideo' format and show file size and return  
but when change format option in '18'  and download file getFilesize() return null and not return really file size 
other option like getTitle() good worked  without problem But getFilesize() not 
you can help me !
thanks

**Comment by norkunas** [comment]
Hey @mohaphez,

Can you give me the link you've tested?

**Comment by mohaphez** [comment]
i have tested this link :[https://www.youtube.com/watch?v=hS5CfP8n_js](https://www.youtube.com/watch?v=hS5CfP8n_js) and when format was set to 18, this command $video = $dl->download($url); returns null but when format is set to bestvideo returns 12247012

**Comment by ysk99** [comment]
as the get-thumbnail function will break the download,,is there any ways to get a thumbnail of video ??

**Comment by norkunas** [comment]
--write-thumbnail                Write thumbnail image to disk
--write-all-thumbnails           Write all thumbnail image formats to disk
