### ISSUE TITLE
ERROR: unable to open for writing: [Errno 13] Permission denied (UBUNTU)

### ISSUE THREAD

**Issue by JackieApkon** [norkunas/youtube-dl-php#30]
I'm sorry my english, is not native language.

I to be with a problem after of finish all process of install.
When goes execute the code, this error occur:

Error Output: ================ ERROR: unable to open for writing: [Errno 13] Permission denied: "Video File...." in /home/.../vendor/symfony/process/Process.php:233 Stack trace: #0 /home/.../vendor/norkunas/youtube-dl-php/src/YoutubeDl.php(102): Symfony\Component\Process\Process->mustRun(Object(Closure)) #1 /var/.../youtube-dl/index.php(25): YoutubeDl\YoutubeDl->download('https://www.you...') #2 {main}

Please, help. What going on? :/

**Comment by norkunas** [comment]
@JackieApkon what is your download path? Because it seems that your user doesn't have permissions to write to it

**Comment by JackieApkon** [comment]
permissions code is 0666 -rw-rw-rw-

**Comment by norkunas** [comment]
@JackieApkon have you tried to set different download path? does that work?

**Comment by JackieApkon** [comment]
Not work. But uncover that works with the permission "execute".

0777
-rwxrwxrwx

**Comment by norkunas** [comment]
So I can't help you further because this is not the library fault

**Comment by JackieApkon** [comment]
Relax. It's alright now. Thanks for the attention :)
