### ISSUE TITLE
how to download 4k video

### ISSUE THREAD

**Issue by wpzzz** [norkunas/youtube-dl-php#32]
like this 
youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' https://www.youtube.com/watch?v=TmDKbUrSYxQ
i got a 4k video, but if i set the format = 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'  in  this php file ,  i will get  720p only

**Comment by CalvinGra** [comment]
--merge-output-format FORMAT
One of mkv, mp4, ogg, webm, flv.

**Comment by Cinerar** [comment]
unfortunatelly files are not merged when using wraper 
if i run youtube-dl from console everything is ok, files are merged.

**Comment by norkunas** [comment]
@Cinerar is your ffmpeg accessible globally?

**Comment by Cinerar** [comment]
Yes it is. i can use it as ffmpeg anywhere, but until i added 'ffmpeg-location' => '/usr/local/bin/ffmpeg' in YoutubeDL creation it was not able to run.

**Comment by norkunas** [comment]
Ok so this needs investigation why process can't access global binaries
