### ISSUE TITLE
Define get-* options

### ISSUE THREAD

**Issue by MichaelBelgium** [norkunas/youtube-dl-php#36]
Why can't I use the youtube-dl options "--get-duration", "--get-title". .... with this? Or is there another way? I'm like checking if the video is already downloaded, if it is then i want the duration, title and path from it.

**Comment by norkunas** [comment]
Because the output parser expects only json to properly return the data for you. And you can get the duration from the `YoutubeDl\Entity\Video` object which is returned after download

**Comment by MichaelBelgium** [comment]
@norkunas I found another way, which is using the option `'skip-download' => true`. Then I can, as you say, still get the duration, title, ... from the Video object. So no need to define them as seperate options after all.
