### ISSUE TITLE
Process fails on windows

### ISSUE THREAD

**Issue by jezzdk** [norkunas/youtube-dl-php#39]
When trying to use the library on windows, it throws a "ProcessFailedException".
This is the entire error message:
```
The command "c:\inetpub\wwwroot\youtube-dl.exe --format 137+140/best --simulate --no-playlist --print-json --ignore-config "https://www.youtube.com/watch?v=iGk5fR-t5AU"" failed.

Exit Code: -1073741819(Unknown error)

Working directory: C:\inetpub\wwwroot\storage\assets\downloads

Output:
================


Error Output:
================
Fatal Python error: Failed to initialize Windows random API (CryptoGen)
```

The command it's trying to execute works fine if I run it manually in the terminal, which makes me think the error is somewhere between the library and the php engine.
I haven't been able to find any solution on google. I'm using the latest version of youtube-dl.exe.

**Comment by jezzdk** [comment]
Upgraded the youtube-dl-php library to use master branch and the error has changed:
```
The command "c:\inetpub\wwwroot\youtube-dl.exe "https://www.youtube.com/watch?v=iGk5fR-t5AU" --no-playlist --print-json --ignore-config "--format=137+140/best" --simulate" failed.

Exit Code: 255(Unknown error)

Working directory: C:\inetpub\wwwroot\storage\assets\downloads

Output:
================


Error Output:
================
Traceback (most recent call last):
File "__main__.py", line 19, in <module>
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_2hklmx2\build\youtube_dl\__init__.py", line 465, in main
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_2hklmx2\build\youtube_dl\__init__.py", line 432, in _real_main
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_2hklmx2\build\youtube_dl\YoutubeDL.py", line 402, in __init__
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_2hklmx2\build\youtube_dl\YoutubeDL.py", line 2267, in _setup_opener
File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp_2hklmx2\build\youtube_dl\utils.py", line 684, in make_HTTPS_handler
File "C:\Python\Python34\lib\ssl.py", line 439, in create_default_context
File "C:\Python\Python34\lib\ssl.py", line 390, in load_default_certs
File "C:\Python\Python34\lib\ssl.py", line 377, in _load_windows_store_certs
PermissionError: [WinError 5] Access is denied
```

Everyone has write access to the working directory, so I don't know why it says access denied.

**Comment by jezzdk** [comment]
Getting closer. Tried the solution mentioned here https://github.com/rg3/youtube-dl/issues/10766 and it works. Only problem is that youtube-dl-php doesn't allow further prefixing of the command.

According to the mentioned solution, the command would need to be changed from:
"c:\inetpub\wwwroot\youtube-dl.exe "https://www.youtube.com/watch?v=iGk5fR-t5AU" --no-playlist --print-json --ignore-config "--format=137+140/best" --simulate"

To something like:
"c:\python\python.exe c:\inetpub\wwwroot\youtube-dl "https://www.youtube.com/watch?v=iGk5fR-t5AU" --no-playlist --print-json --ignore-config "--format=137+140/best" --simulate".

I can hack the YoutubeDL class by adding `array_unshift($arguments, 'C:\Python\python.exe');` to the createProcess() method and then it works, but you know...

**Comment by jezzdk** [comment]
Created pull request.

**Comment by norkunas** [comment]
What about $yt->setBinPath('C:\Python\python.exe c:\inetpub\wwwroot\youtube-dl.exe'); ? Could you try it?

**Comment by jezzdk** [comment]
I tried it, but it gets quoted in a way so the command fails:
`"C:\Python\python.exe c:\inetpub\wwwroot\youtube-dl.exe"`

Should be quoted like this:
`"C:\Python\python.exe" "c:\inetpub\wwwroot\youtube-dl.exe"`

**Comment by norkunas** [comment]
OK, merged ;)

**Comment by usamamashkoor** [comment]
@jezzdk and @norkunas i am facing the same error can you please let me know how can i fix this issue. 
Thanks in advance.  
> Error Output:
> ================
> Fatal Python error: Failed to initialize Windows random API (CryptoGen)

**Comment by norkunas** [comment]
@usamamashkoor so have you tried `$yt->setPythonPath()`?

**Comment by Achilles718611** [comment]
I've got the same error.
I set python path, but got the same error.

**Comment by norkunas** [comment]
> I've got the same error.
> I set python path, but got the same error.

Could you dump the generated command line?

**Comment by Achilles718611** [comment]
![image](https://user-images.githubusercontent.com/31845458/82770291-9dd62300-9e6a-11ea-9888-180fde37bd38.png)

Please check.
If I run command in terminal, it works.

**Comment by norkunas** [comment]
Did you try to call `$dl->setPythonPath()` to configure the path to python ?

**Comment by Achilles718611** [comment]
![image](https://user-images.githubusercontent.com/31845458/82792132-79e20400-9ea1-11ea-9871-458415d2e60d.png)

I set python path.
I use Pyton 3.6.
As you can see it doens't worke even I set Python path.

**Comment by Achilles718611** [comment]
![image](https://user-images.githubusercontent.com/31845458/82792240-ab5acf80-9ea1-11ea-8beb-2c54f2d07b8f.png)

**Comment by norkunas** [comment]
Okay, so now it's a different error. From the context I can only guess that somehow your environment configuration breaks this and from here I can't help you anymore, so you'll have to search the solution based on the error you have now. Maybe this would help for you https://github.com/appveyor/ci/issues/1995#issuecomment-589987565

**Comment by Achilles718611** [comment]
I think it's not environment problem, if I enter command on terminal directly, it works.

**Comment by norkunas** [comment]
I think still it is. The started process probably doesn't get all needed env vars and so it fails.
Could you try to directly edit symfony Process code and add for example `PYTHONPATH` and 'SYSTEMROOT' env vars with proper values? See https://github.com/mgedmin/check-manifest/issues/52

**Comment by Achilles718611** [comment]
Can you tell me in detail, please?

**Comment by Achilles718611** [comment]
I think it's not related with youtube dl library, maybe it's related with symfony process.
Thanks for your help.
