### ISSUE TITLE
Add progress function

### ISSUE THREAD

**Issue by pionut196** [norkunas/youtube-dl-php#41]
Can you do what this guy do?

Example #3: With progress function

```
require_once 'vendor/autoload.php';

use PHPYoutubeDl\PHPYoutubeDl;

function showProgress($downloaded_size, $download_size){
	echo $downloaded_size / $download_size;
	echo PHP_EOL;
	flush();
}

$php_youtube_dl = new PHPYoutubeDl("http://www.youtube.com/watch?v=xxxxxx");
$php_youtube_dl->setProgressCallback('showProgress');
$php_youtube_dl->startDownload();
```
source: https://github.com/aladdindev/php-youtube-dl
also maybe this will help: https://askubuntu.com/questions/635504/youtube-dl-file-download-progress-with-zenity-progress-bar
PS: No, i cannot do it by myself

**Comment by norkunas** [comment]
Maybe, but currently I don't have much time to implement that.

**Comment by pionut196** [comment]
Thank you! I will wait.
Some advices will be welcome!

**Comment by norkunas** [comment]
It is possible to debug the process stream providing a debug callback like:
```
$yt->debug(function ($type, $buffer) {
    if (\Symfony\Component\Process\Process::OUT === $type) {
       // read $buffer
    }
});
```
So you could read the stream output and determine the progress by yourself.

Or you could implement `progress($downloadSize, $eta, ...)` method with `private $progress` property and make a PR for it. But keep in mind that you need to provide the default callback to `mustRun` method [#L121](https://github.com/norkunas/youtube-dl-php/blob/master/src/YoutubeDl.php#L121) and in that callback call the `progress` or `debug` if they are defined.

**Comment by norkunas** [comment]
Related to #35

**Comment by norkunas** [comment]
Handled in 30645d4
