### ISSUE TITLE
Problem with Linux command 

### ISSUE THREAD

**Issue by pionut196** [norkunas/youtube-dl-php#44]
Everything worked until yesterday, now:

Fatal error: Uncaught YoutubeDl\Exception\NotFoundException in /var/www/html/vendor/norkunas/youtube-dl-php/src/YoutubeDl.php:173 Stack trace: #0 /var/www/html/vendor/norkunas/youtube-dl-php/src/YoutubeDl.php(123): YoutubeDl\YoutubeDl->handleException(Object(Symfony\Component\Process\Exception\ProcessFailedException)) #1 /var/www/html/api.php(12): YoutubeDl\YoutubeDl->download('https://www.you...') #2 {main} thrown in /var/www/html/vendor/norkunas/youtube-dl-php/src/YoutubeDl.php on line 173

looks like it`s adding a text at the end of command sometime:

youtube-dl --extract-audio --audio-format mp3 --audio-quality 0 --output &quot;%(id)s.%(ext)s&quot; --no-playlist --print-json --ignore-config 'https://www.youtube.com/watch?v=QQcQDbpDH_o'

i`m talking about the " &quot; " thing.
tested on 2 different server both of them on ubuntu 16.04 and 17
both of them are on php 7.0

**Comment by norkunas** [comment]
Hey @pionut196,

Could you give me simple snippet to reproduce this?

**Comment by norkunas** [comment]
@pionut196 could you try to update to the v0.3.4 and check if the problem still persists?

**Comment by pionut196** [comment]
fixed by update, thanks
