### ISSUE TITLE
onProgress not available in 0.3.5

### ISSUE THREAD

**Issue by DimitriCK7** [norkunas/youtube-dl-php#51]
I installed this beautiful package as instructed in the readme
```
composer require norkunas/youtube-dl-php
```
This installs the 0.3.5 version of this package. Unfortunately the new onProgress function (also described in the readme) doesn't exists in this [version](https://github.com/norkunas/youtube-dl-php/blob/v0.3.5/src/YoutubeDl.php).
Any change of deploying a new version containing this change?

**Comment by norkunas** [comment]
Just use dev-master currently.

**Comment by DimitriCK7** [comment]
I prefer not to pull in dev-master versions but for now I'll make an exception.
Thanks for the info and this package (saves me a ton of time)

**Comment by norkunas** [comment]
There is no plans to introduce any breaking changes. I'm glad you like it :+1:
