### ISSUE TITLE
Fatal Python error: Failed to initialize Windows random API (CryptoGen)

### ISSUE THREAD

**Issue by audas** [norkunas/youtube-dl-php#52]
Windows youtube-dl.exe is definitely found and working - path set etc.

When I remove the parameters in the Process function as per this post

https://stackoverflow.com/questions/44735057/resolve-relative-urls-of-youtube-using-php

the error is no longer thrown however it simply times out.

The youtube-dl command does NOT work without setting the binPath - not found - and when it is set the above error occurs.

The youtube-dl is found and works by calling a straight shell_exec on the youtube-dl with video - AND it works from command line - it appears this is entirely something wrong with the package.

I have seen some earlier suggestions of putting the Python path in the set bin path - however this appears to be prior to the Python being embedded in the exe and failed when I tested it.

Any thoughts ?

**Comment by norkunas** [comment]
#53 maybe just try to update to the dev-master for now

**Comment by audas** [comment]
Thanks for the reply - this did not help either.

Ironically I spent some time on this as I felt it was an highly complicated piece of kit - so I just engaged with youtube-dl myself constructing my own commands - no harder than ffmpeg itself.

So - just running with it native - thanks.
