### ISSUE TITLE
Where should i keep youtube-dl.exe

### ISSUE THREAD

**Issue by rafayexalter** [norkunas/youtube-dl-php#53]
Sorry for asking a dumb question, it's giving me a headache. I have installed everything via composer. Now I don't know what to do next, I have tried my best and now finally I am stopped at this error.

`ERR > Fatal Python error: Failed to initialize Windows random API (CryptoGen)`

The second thing I don't understand I will be moving this project from localhost to online so where I will keep youtube-dl.exe?

**Comment by norkunas** [comment]
Hello,

There was issue about this earlier #39, you should set the python path `$yt->setPythonPath(..)` and `$yt->setBinPath('/path/to/youtube-dl.exe')`.

You can have it anywhere but the path needs to set.

**Comment by rafayexalter** [comment]
Thanks for replying, now it says:

`Fatal error: Uncaught Error: Call to undefined method YoutubeDl\YoutubeDl::setPythonPath() in C:\xampp\htdocs\scripts\new\index.php:17 Stack trace: #0 {main} thrown in C:\xampp\htdocs\scripts\new\index.php on line 17`


If I do like this **$dl->setBinPath('C:\Python\python.exe c:\xampp\htdocs\scripts\youtube-dl.exe');**

then it shows:
`ERR > The filename, directory name, or volume label syntax is incorrect.`

**Comment by norkunas** [comment]
Because python path is introduced only in dev-master, so you should update

**Comment by rafayexalter** [comment]
Okay, I have updated, PythonPath method is available and now I see this error :D

`ERR > c:\Python\python.exe: can't find '__main__' module in 'c:/xampp/htdocs/scripts/youtube-dl.exe'`

**Comment by rafayexalter** [comment]
It's working, removed python path, sorry for being so dumb.

Thank you so much

**Comment by norkunas** [comment]
No prob. ;) I just don't understand why python throws that error

**Comment by rafayexalter** [comment]
Sorry, I'm new to this scripting thing with python so I really don't know about that problem.

BTW, Will I have to change anything if I upload this script to my hosting?

**Comment by norkunas** [comment]
Depends on the host

**Comment by norkunas** [comment]
Why do you need to get json? After download you already get the Video object which contains all the data from json

**Comment by rafayexalter** [comment]
I got it, Thank you. you can close this issue.

Thank you so much again

**Comment by norkunas** [comment]
Have a good day :wink:
