### ISSUE TITLE
POST & GET 

### ISSUE THREAD

**Issue by phobienbuon** [norkunas/youtube-dl-php#55]
Hi, Tomas

how do i POST the URL to $dl->download("https://www.youtube.com/watch?v=wM8ytYa5sHw");
$dl->download($_GET[link]);
example: 

```
$reqUrl = $_GET[link];
require __DIR__ . '/vendor/autoload.php';
use YoutubeDl\YoutubeDl;
$dl = new YoutubeDl([
    'extract-audio' => true,
    'audio-format' => 'mp3',
    'audio-quality' => 0, // best
    'output' => '%(title)s.%(ext)s',
]);
$dl->setDownloadPath('./');
$video = $dl->download($reqUrl);
```

i works wonderful but get and post wont send the link to download?

Thanks form your help

Hi Tomas, Thanks for reply
i've tried both methods,
none of them worked.
i mean either method.

**Comment by norkunas** [comment]
Hey,

If you are making GET request then access `$_GET['link']` and if making POST request then access `$_POST['link']` if this is not what are you asking please explain a little more what are you trying to do :)

**Comment by phobienbuon** [comment]
i think problem is here>
when i do `php download.php` in command line the it works, when i run on browser then this is the errors:

PHP Fatal error:  Uncaught exception 'YoutubeDl\\Exception\\NotFoundException' in /home/dan/www/yt/vendor/norkunas/youtube-dl-php/src/YoutubeDl.php:495\nStack trace:\n#0 /home/dan/www/yt/vendor/norkunas/youtube-dl-php/src/YoutubeDl.php(243): YoutubeDl\\YoutubeDl->handleException(Object(Symfony\\Component\\Process\\Exception\\ProcessFailedException))\n#1 /home/dan/www/yt/test.php(15): YoutubeDl\\YoutubeDl->download('https://www.you...')\n#2 {main}\n  thrown in /home/dan/www/yt/vendor/norkunas/youtube-dl-php/src/YoutubeDl.php on line 495

**Comment by norkunas** [comment]
What is the url of the video you are trying to download?

**Comment by phobienbuon** [comment]
Hi, Tomas,
Any youtube url would appears the same error

**Comment by norkunas** [comment]
Could you share your full download.php code?

**Comment by phobienbuon** [comment]
```
$reqUrl = $_GET[link];
require __DIR__ . '/vendor/autoload.php';
use YoutubeDl\YoutubeDl;
$dl = new YoutubeDl([
    'extract-audio' => true,
    'audio-format' => 'mp3',
    'audio-quality' => 0, // best
    'output' => '%(title)s.%(ext)s',
]);
$dl->setDownloadPath('./');
$video = $dl->download($reqUrl);
```
i use `download.php?link=youtube_link`

**Comment by phobienbuon** [comment]
i think i sorted it. no idea why

**Comment by norkunas** [comment]
And what do you changed? I think the problem could be your `$reqUrl = $_GET[link]` as you are providing a key to get as a constant not as the parameter. Right way to write is `$reqUrl = $_GET['link']` or `$_POST['link']`.

**Comment by phobienbuon** [comment]
i think you're right there. got it sorted
thanks Tomas

**Comment by norkunas** [comment]
Good :+1: closing then.
