### ISSUE TITLE
How use Download progress?

### ISSUE THREAD

**Issue by ekam230** [norkunas/youtube-dl-php#56]

**Comment by norkunas** [comment]
What's not clear about it from the README?

**Comment by ekam230** [comment]
I use so. don't work.

<?php
require __DIR__ . '/vendor/autoload.php';

use YoutubeDl\YoutubeDl;

$dl = new YoutubeDl([
    'extract-audio' => true,
    'audio-format' => 'mp3',
    'audio-quality' => 0, // best
    'output' => '%(title)s.%(ext)s',
]);
$dl->setDownloadPath('/home/user/downloads');

$video = $dl->download('https://www.youtube.com/watch?v=oDAw7vW7H0c');

$dl->onProgress(function ($progress) {
    $percentage = $progress['percentage'];
    $size = $progress['size'];
    $speed = $progress['speed'] ?? null;
    $eta = $progress['eta'] ?? null;
    
    echo "Percentage: $percentage; Size: $size";
    if ($speed) {
        echo "; Speed: $speed";
    }
    if ($eta) {
        echo "; ETA: $eta";
    }
    // Will print: Percentage: 21.3%; Size: 4.69MiB; Speed: 4.47MiB/s; ETA: 00:01
});

?>

**Comment by norkunas** [comment]
Please be more clear, because "don't work" doesn't explain anything to me. Also your callback must be set before downloading the video, maybe that's the reason.

**Comment by ekam230** [comment]
I use 
```
$dl->onProgress(function ($progress) {
    $percentage = $progress['percentage'];
    $size = $progress['size'];
    $speed = $progress['speed'] ?? null;
    $eta = $progress['eta'] ?? null;
    
    echo "Percentage: $percentage; Size: $size";
    if ($speed) {
        echo "; Speed: $speed";
    }
    if ($eta) {
        echo "; ETA: $eta";
    }
    // Will print: Percentage: 21.3%; Size: 4.69MiB; Speed: 4.47MiB/s; ETA: 00:01
});
```

in three any places, code don't work. page don't open, when i use code. 

```
<?php
require __DIR__ . '/vendor/autoload.php';

use YoutubeDl\YoutubeDl;
**I use code HERE!**

$dl = new YoutubeDl([
    'extract-audio' => true,
    'audio-format' => 'mp3',
    'audio-quality' => 0, // best
    'output' => '%(title)s.%(ext)s',
]);

**HERE!**
$dl->setDownloadPath('/home/user/downloads');
**AND HERE!**
$video = $dl->download('https://www.youtube.com/watch?v=oDAw7vW7H0c');

?>
```

**Comment by norkunas** [comment]
Please check your logs if you are getting some errors or at least give some more information.. Like library version, your OS, php version..

**Comment by norkunas** [comment]
Or run your script in the terminal `php your_script.php` and paste the output here.

**Comment by ekam230** [comment]
PHP Parse error:  syntax error, unexpected '?' in /home/admin/web/sdmns.ru/public_html/conf2.php on line 20

**Comment by ekam230** [comment]
INFO FILE
[info.txt](https://github.com/norkunas/youtube-dl-php/files/1560410/info.txt)

**Comment by ekam230** [comment]
i delete ?? from file. And execute them. 
Error:
`PHP Fatal error:  Call to undefined method YoutubeDl\YoutubeDl::onProgress() in /home/admin/web/sdmns.ru/public_html/conf2.php on line 16
`

**Comment by ekam230** [comment]
I verify my server. Update PHP from 5.4 to 7.1. 

Now have next error:
```
PHP Fatal error:  Uncaught Error: Call to undefined method YoutubeDl\YoutubeDl::                           onProgress() in /home/admin/web/sdmns.ru/public_html/conf2.php:16
Stack trace:
#0 {main}
  thrown in /home/admin/web/sdmns.ru/public_html/conf2.php on line 16

```

**Comment by ekam230** [comment]
Great! All work good! Sorry for my issues! I replace files of your script and all works good. I install your script from composer and he download old version(october)
