### ISSUE TITLE
Localhost to Hosting

### ISSUE THREAD

**Issue by rafayexalter** [norkunas/youtube-dl-php#57]
Hello again,

I really don't know this is issue of youtube-dl-php or not, you are an expert that's why I am asking from you :D 

Well, I just copied everything to my hosting and changed bin path and downloads path to

`$youtubedl->setBinPath('/home/onlinevi/public_html/bin/youtube-dl.exe');
$youtubedl->setDownloadPath('/home/onlinevi/public_html/downloads');`

**In error_log I'm getting these errors**
`Stack trace:
#0 /home/onlinevi/public_html/vendor/norkunas/youtube-dl-php/src/YoutubeDl.php(231): Symfony\Component\Process\Process->__construct(Array)
#1 /home/onlinevi/public_html/vendor/norkunas/youtube-dl-php/src/YoutubeDl.php(131): YoutubeDl\YoutubeDl->createProcess(Array)
#2 /home/onlinevi/public_html/file-download.php(34): YoutubeDl\YoutubeDl->download('https://www.you...')
#3 {main}
  thrown in /home/onlinevi/public_html/vendor/symfony/process/Process.php on line 147`

If you are free, can you help please, what should I do?

P.S: I have cPanel shared hosting...

**Comment by norkunas** [comment]
Hey, which OS your hosting uses?

**Comment by rafayexalter** [comment]
It's Linux...

**Comment by norkunas** [comment]
So you can't run windows binaries on linux ;)

**Comment by rafayexalter** [comment]
Should I buy windows hosting? or is there any other thing should I do for linux

**Comment by rafayexalter** [comment]
Will it work on **WINDOWS PLESK HOSTING**?

Let me know so I change my hosting

Thank you so much

**Comment by norkunas** [comment]
I think you'll need VPS because hostings doesn't allow to store and run binaries, but you could try to write to support.

**Comment by rafayexalter** [comment]
Okay, so I just uploaded the script to windows VPS, getting these errors. what's next? :D

`[15-Dec-2017 12:02:08 UTC] PHP Fatal error:  Uncaught Symfony\Component\Process\Exception\ProcessFailedException: The command ""C:/Inetpub/vhosts/exampledomain.com/httpdocs/bin/youtube-dl.exe" "https://www.youtube.com/watch?v=xxxxxxxxx" --no-playlist --ignore-config --write-info-json --extract-audio --audio-format=mp3 --audio-quality=0 "--output="^%"(title)s."^%"(ext)s"" failed.

Exit Code: 255(Unknown error)

Working directory: C:/Inetpub/vhosts/exampledomain.com/httpdocs/downloads

Output:
================


Error Output:
================
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\__init__.py", line 465, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\__init__.py", line 432, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp10f7prtw\build\youtube_dl\YoutubeDL.py", line 410, in __init__
  File "C:\Users\dst\AppDat in C:\Inetpub\vhosts\exampledomain.com\httpdocs\vendor\symfony\process\Process.php on line 239`

**Comment by norkunas** [comment]
Sorry, I don't code anymore in windows env..
Have you tried `$yt->setPythonPath()` ?

**Comment by rafayexalter** [comment]
Just tried it now, is there anything wrong I am doing in coding?

```
[15-Dec-2017 12:19:29 UTC] PHP Fatal error:  Uncaught Symfony\Component\Process\Exception\ProcessFailedException: The command ""C:/Program Files (x86)/Plesk/python/python.exe" "C:/Inetpub/vhosts/mydomain.com/httpdocs/bin/youtube-dl.exe" "https://www.youtube.com/watch?v=xxxxxxxx" --no-playlist --ignore-config --write-info-json --extract-audio --audio-format=mp3 --audio-quality=0 "--output="^%"(title)s."^%"(ext)s"" failed.

Error Output:
================
Access is denied.
 in C:\Inetpub\vhosts\mydomain.com\httpdocs\vendor\symfony\process\Process.php:239
Stack trace:
#0 C:\Inetpub\vhosts\mydomain.com\httpdocs\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php(147): Symfony\Component\Process\Process->mustRun(Object(Closure))
#1 C:\Inetpub\vhosts\mydomain.com\httpdocs\file-download.php(32): YoutubeDl\YoutubeDl->download('https://www.you...')
#2 {main}
  thrown in C:\Inetpub\vhosts\mydomain.com\httpdocs\vendor\symfony\process\Process.php on line 239
```

**Comment by norkunas** [comment]
I don't think so but from current error you can see that your php script doesn't have sufficient permissions to execute python/youtube-dl

**Comment by rafayexalter** [comment]
I think you are thinking right, when I run this command it's working fine...

`C:\bin\youtube-dl.exe "https://www.youtube.com/watch?v=oDAw7vW7H0c" --no-playlist --ignore-config --write-info-json --extract-audio --audio-format=mp3 --audio-quality=0 "--output="^%"(title)s."^%"(ext)s"`

Do you know anyone who can help with this? if it doesn't solve then my all work will be useless haha

and when I open the URL in the browser, it shows this:

I tried to google but failed to get any solution

`Fatal error: Uncaught Symfony\Component\Process\Exception\ProcessFailedException: The command "C:\bin\youtube-dl.exe "https://www.youtube.com/watch?v=oDAw7vW7H0c" --no-playlist --ignore-config --write-info-json --extract-audio --audio-format=mp3 --audio-quality=0 "--output="^%"(title)s."^%"(ext)s"" failed. Exit Code: 1(General error) Working directory: C:\Inetpub\vhosts\domain.com\httpdocs\downloads Output: ================ Error Output: ================ Access is denied. in C:\Inetpub\vhosts\domain.com\httpdocs\vendor\symfony\process\Process.php:239 Stack trace: #0 C:\Inetpub\vhosts\domain.com\httpdocs\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php(154): Symfony\Component\Process\Process->mustRun(Object(Closure)) #1 C:\Inetpub\vhosts\domain.com\httpdocs\index.php(17): YoutubeDl\YoutubeDl->download('https://www.you...') #2 {main} thrown in C:\Inetpub\vhosts\domain.com\httpdocs\vendor\symfony\process\Process.php on line 239`

**Comment by norkunas** [comment]
If you have access to the terminal then try to run your script in it to check if the problem is related with your apache/nginx user or something else

**Comment by rafayexalter** [comment]
I installed xampp on VPS and everything is working fine lol, I will ask VPS provider for help :D

Thank you for bearing me...

**Comment by norkunas** [comment]
No problem :)

**Comment by rafayexalter** [comment]
Hi, I'm using Ubuntu in VMware to do things from start, I have installed the youtube-dl, xampp, composer.

So, What modification should I do in basic Download Video code?

youtube-dl is working in the terminal, here is the error I'm getting. I know I'm becoming a headache for you I just need some time to work on these things. 

`Fatal error: Uncaught Symfony\Component\Process\Exception\ProcessFailedException: The command "'/usr/local/bin/youtube-dl' 'https://www.youtube.com/watch?v=oDAw7vW7H0c' '--no-playlist' '--ignore-config' '--write-info-json' '--continue' '--format=bestvideo'" failed. Exit Code: 1(General error) Working directory: /home/abdulrafay/Downloads Output: ================ Error Output: ================ Traceback (most recent call last): File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/usr/local/bin/youtube-dl/__main__.py", line 16, in <module> File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 15, in <module> File "/usr/local/bin/youtube-dl/youtube_dl/options.py", line 8, in <module> File "/usr/local/bin/youtube-dl/youtube_dl/downloader/__init__.py", line 3, in <module> File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 10, in <mo in /opt/lampp/htdocs/youtube-dl/vendor/symfony/process/Process.php on line 239`

**Comment by MhmdSalah** [comment]
hello norkunas are you available for a work related to this repo? please give me your email.

**Comment by norkunas** [comment]
Hi, you can find my email in composer.json file :)
