### ISSUE TITLE
heroku deploy

### ISSUE THREAD

**Issue by nk932714** [norkunas/youtube-dl-php#59]
please add composer lock

`-----> PHP app detected

 !     ERROR: Your 'composer.json' lists dependencies inside 'require',

       but no 'composer.lock' was found. Please run 'composer update' to

       re-generate 'composer.lock' if necessary, and commit it into your

       repository. For more information, please refer to the docs at

       https://devcenter.heroku.com/articles/php-support#activation

 !     Push rejected, failed to compile PHP app.

 !     Push failed

`

**Comment by norkunas** [comment]
This library doesn't meant to be used as a project but instead as a dependency in your project, so no I won't add composer.lock here.

**Comment by nk932714** [comment]
Thanks for your reply @norkunas
