### ISSUE TITLE
How to get download links

### ISSUE THREAD

**Issue by ahm786** [norkunas/youtube-dl-php#61]
Hi,

Is there a way to get a list of download links for a youtube video rather than downloading the file? youtube-dl has this option, so how can it be done with this PHP wrapper?

**Comment by norkunas** [comment]
Hi @ahm786, don't know if you already found a way for this but simply you can just configure library with 'skip-download' option and it will give you download links in the `$video->getFormats()`

**Comment by ahm786** [comment]
Yup, got it :) Thanks!
