### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by ahm786** [norkunas/youtube-dl-php#62]
I've been keeping track of the CPU usage (with htop) while the youtube-dl script is executed, and it spikes to 100% whenever the script runs. If multiple instances of the script are executed at the same time, then it freezes the server.

Why is that? Any way to fix this problem?

**Comment by norkunas** [comment]
Hmm, don't know what to say, never ran into this :expressionless:

**Comment by norkunas** [comment]
Is this only when running this library or also when running youtube-dl directly?

**Comment by ahm786** [comment]
Happens with youtube-dl also, so I guess it's a problem with that :?

**Comment by ahm786** [comment]
I really want to use this PHP wrapper, but the CPU usage is the only issue for me now. Hope I can find a way out.

**Comment by norkunas** [comment]
Then sorry, but I cannot help further :neutral_face:

**Comment by norkunas** [comment]
Try to open issue directly in https://github.com/rg3/youtube-dl

**Comment by norkunas** [comment]
Also you could try --verbose option when running directly with youtube-dl too see if there are any warnings about this

**Comment by ahm786** [comment]
Thanks, I opened an issue there now.

It happens with all links, including Instagram. Let me check --verbose

**Comment by ahm786** [comment]
Nope, --verbose doesn't throw any warnings. Just some basic information:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-j', u'https://www.youtube.com/watch?v=hWFDujYzvbI', u'--skip-download', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.02.04
[debug] Python version 2.7.13 (CPython) - Linux-4.14.12-x86_64-linode92-x86_64-with-Ubuntu-17.04-zesty
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Default format spec: bestvideo+bestaudio/best
