### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by chadul** [norkunas/youtube-dl-php#65]
Fatal error: Uncaught exception 'Symfony\Component\Process\Exception\RuntimeException' with message 'The Process class relies on proc_open, which is not available on your PHP installation.' in /usr/share/nginx/html/m.vuclip.club/vendor/symfony/process/Process.php:147 Stack trace: #0 /usr/share/nginx/html/m.vuclip.club/vendor/norkunas/youtube-dl-php/src/YoutubeDl.php(516): Symfony\Component\Process\Process->__construct(Array) #1 /usr/share/nginx/html/m.vuclip.club/vendor/norkunas/youtube-dl-php/src/YoutubeDl.php(238): YoutubeDl\YoutubeDl->createProcess(Array) #2 /usr/share/nginx/html/m.vuclip.club/tes.php(15): YoutubeDl\YoutubeDl->download('https://www.you...') #3 {main}

**Comment by norkunas** [comment]
So the error explains what is wrong. :)

**Comment by chadul** [comment]
OK solved it's on my php
