### ISSUE TITLE
Error while trying to download

### ISSUE THREAD

**Issue by jayzienS** [norkunas/youtube-dl-php#66]
Hello, im getting HTTP ERROR 500 while using the code mentioned below. Any ideas why?
This is the /var/log/apache2/error.log output:

> [Wed Apr 11 23:06:15.339320 2018] [:error] [pid 1491] [client xx.xx.xx.xx:xxxxx] PHP Fatal error:  Uncaught Symfony\\Component\\Process\\Exception\\ProcessFailedException: The command "'/usr/local/bin/youtube-dl' 'https://www.youtube.com/watch?v=XOVI851gAJg' '--no-playlist' '--ignore-config' '--write-info-json' '--extract-audio' '--audio-format=mp3' '--audio-quality=0' '--output=%(title)s.%(ext)s'" failed.\n\nExit Code: 1(General error)\n\nWorking directory: /home/mapmanager\n\nOutput:\n================\n[youtube] XOVI851gAJg: Downloading webpage\n[youtube] XOVI851gAJg: Downloading video info webpage\n[youtube] XOVI851gAJg: Extracting video information\n[youtube] XOVI851gAJg: Downloading js player vflSawkIt\n[info] Writing video description metadata as JSON to: DJ_Khaled_-_I_m_the_One_ft._Justin_Bieber_Quavo_Chance_the_Rapper_Lil_Wayne_Lyrics_Lyric_Video.info.json\n\n\nError Output:\n================\nWARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.\nWARNING: Writing cache to u'/var/www/.cache/youtube-dl/youtube-sigfuncs/js_vflSawkIt in /var/www/html/ytconverter/vendor/symfony/process/Process.php on line 239

PHP:
```
<?php
require __DIR__ . '/vendor/autoload.php';

use YoutubeDl\YoutubeDl;

$dl = new YoutubeDl([
    'extract-audio' => true,
    'audio-format' => 'mp3',
    'audio-quality' => 0, // best
    'output' => '%(title)s.%(ext)s',
]);
$dl->setDownloadPath('/home/mapmanager');

$video = $dl->download('https://www.youtube.com/watch?v=XOVI851gAJg');
```

**Comment by norkunas** [comment]
Hello, is your directory writable?
