### ISSUE TITLE
Downloading playlist?

### ISSUE THREAD

**Issue by csimpi** [norkunas/youtube-dl-php#67]
Hi, when I try to download playlist, I'm getting 
`RuntimeException: Response can't be decoded error.`
This wrapper can't handle the playlist links, only single tracks?
Thx,
Peter

**Comment by norkunas** [comment]
Hi, yes this library doesn't support downloading playlists.

**Comment by csimpi** [comment]
Aww, that's too bad, I like this lib, I wanted to add more features my converter website, but that's not gonna happen :)) thx for the quick answer and for you awesome work

**Comment by norkunas** [comment]
Maybe in v2, but i've made this lib for my own use case for single videos, supporting playlists download needs some spare time which I don't have currently :) but you can always extend this library. I'm always trying to follow semver not to break anything :)
