### ISSUE TITLE
re-stream?

### ISSUE THREAD

**Issue by vaguiners** [norkunas/youtube-dl-php#69]
its possible to stream the youtube video?
the goal is to let user be free from google servers

**Comment by norkunas** [comment]
Hello @vaguiners,

I've created this library exactly for downloading files to machine directly, but if you'll find an easy way to implement this I will happily accept the PR :)

This is from [youtube-dl documentation](https://github.com/rg3/youtube-dl):
> You can use -o - to let youtube-dl stream a video to  stdout, or simply allow the player to download the files written by youtube-dl in turn.

> You will first need to tell youtube-dl to stream media to stdout with -o -, and also tell your media player > to read from stdin (it must be capable of this for streaming) and then pipe former to latter. For example, > streaming to vlc can be achieved with:
> youtube-dl -o - "https://www.youtube.com/watch?v=BaW_jenozKcj" | vlc -
