### ISSUE TITLE
How to disable playlist downloading?

### ISSUE THREAD

**Issue by jjvvx** [norkunas/youtube-dl-php#71]
I don't want to support playlists in my application. Is there an easy way to not allow playlists?

**Comment by norkunas** [comment]
Hmm, this library already disables playlist downloading, what problem do you have?

**Comment by jjvvx** [comment]
My code before downloading the file it runs with `--skip-download` first to verify that the video is valid (no 18+ videos, has a supported format, etc.) but when I tried to give it a playlist URL it hung for around an hour downloading metadata for each individual YouTube video. I could filter out the URL and keep a big list of regular expressions for every website, I'm just asking if there's a more youtube-dl level solution than that.

**Comment by norkunas** [comment]
I did not found any option in youtube-dl itself to prevent playlist download. Maybe you could send a PR with updated `$blacklist` links, because there is already a link preventing to download playlists from soundcloud.
