### ISSUE TITLE
Fatal error: Uncaught Symfony\Component\Process\Exception\RuntimeException: The provided cwd does not exist

### ISSUE THREAD

**Issue by garry911** [norkunas/youtube-dl-php#72]
hi 

I am facing the issue here when i use  .
$video = $dl->download('url');
Fatal error: Uncaught Symfony\Component\Process\Exception\RuntimeException: The provided cwd does not exist. 
YoutubeDl\YoutubeDl->download('https://www.vik...') #4 {main} thrown in C:\xampp\htdocs\nork\vendor\symfony\process\Process.php on line 301 .

please  help me out :) .

**Comment by garry911** [comment]
Yes I set it now . I have used your example . 
$yt->setBinPath('C:\xampp\htdocs\nork\usr\local\bin');
$yt->setDownloadPath('D:/');
$video = $yt->download('https://www.youtube.com/watch?v=C1Tcfn2ZEgg');

// The above video link is working using cmd . 
// but here it is  facing some error  .
 
Fatal error: Uncaught Symfony\Component\Process\Exception\ProcessFailedException: The command ""/usr/bin/youtube-dl" "https://www.youtube.com/watch?v=C1Tcfn2ZEgg" --no-playlist --ignore-config --write-info-json" failed. Exit Code: 1(General error) Working directory: D:/ Output: ================ Error Output: ================ The system cannot find the path specified. in C:\xampp\htdocs\nork\vendor\symfony\process\Process.php:223 Stack trace: #0 C:\xampp\htdocs\nork\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php(154): Symfony\Component\Process\Process->mustRun(Object(Closure)) #1 C:\xampp\htdocs\nork\index.php(13): YoutubeDl\YoutubeDl->download('https://www.you...') #2 {main} thrown in C:\xampp\htdocs\nork\vendor\symfony\process\Process.php on line 223

**Comment by garry911** [comment]
Hi  , 
Thanks for the help i can use getExtractorsList() , now  .
 :+1: 
and what method can extract the subs ?


Thanks .

**Comment by norkunas** [comment]
Hi, how did you write it? Because from what can I see you didn't provide the url from where extract subtitles

**Comment by garry911** [comment]
I have made the correction now and calling download method with   url  & i need to have subtitles  with skip download option .

**Comment by norkunas** [comment]
Did you try to instantiate it like?:
```
$dl = new YoutubeDl([
    'skip-download' => true,
    'all-subs' => true,
]);
```

I don't know if youtube-dl itself supports download subtitles without video, but still worth to try :)

**Comment by garry911** [comment]
Thanks for the help .
its working fast on my localhost  .
:+1:  
thanks

**Comment by garry911** [comment]
Hi

do the script need to set up root to run it on server  ?

**Comment by garry911** [comment]
hello 
 another error is .
Fatal error: in root/vendor/symfony/process/Process.php on line 223

**Comment by garry911** [comment]
Hello . 

When i ran this on the server i get fatal error , while the script runs fine on my localhost   .
Anything that i am missing ? 
  
 Fatal error: in /var/www/html/apps/subs/vendor/symfony/process/Process.php on line 223 

Thanks .

**Comment by norkunas** [comment]
> Did you try to instantiate it like?:
> 
> ```
> $dl = new YoutubeDl([
>     'skip-download' => true,
>     'all-subs' => true,
> ]);
> ```
> I don't know if youtube-dl itself supports download subtitles without video, but still worth to try :)
