### ISSUE TITLE
 Syntax error: ")" unexpected

### ISSUE THREAD

**Issue by garry911** [norkunas/youtube-dl-php#73]
hi 
 
 I am  stuck with this error .What this is ? Any thing  that i am missing ? 

 Message: The command "'/var/www/html/apps/coredev/usr/local/bin/youtube-dl.exe' 'https://www.viki.com/videos/1119776v-trailer-3' '--skip-download' '--no-playlist' '--ignore-config' '--write-info-json' '--write-sub' '--write-auto-sub' '--abort-on-error' '--skip-download' '--all-subs'" failed. Exit Code: 2(Misuse of shell builtins) Working directory: /var/www/html/apps/coredev/downloads Output: ================ Error Output: ================ /var/www/html/apps/coredev/usr/local/bin/youtube-dl.exe: 1: /var/www/html/apps/coredev/usr/l ocal/bin/youtube-dl.exe: MZ����@���: not found /var/www/html/apps/coredev/usr/local/bin/youtube-dl.exe: 2: /var/www/html/apps/coredev/usr/local/bin/youtube-dl.exe: $��}ŶHŶHŶH�+�HǶH�+�HĶH�+�HǶH�΀H¶HŶH��H�+�H߶H�+�HĶH�+�HĶH�+�HĶHRichŶHPELOzFT�: not found /var/www/html/apps/coredev/usr/local/bin/youtube-dl.exe: 3: /var/www/html/apps/coredev/usr/local/bin/youtube-dl.exe: Syntax error: ")" unexpected

**Comment by garry911** [comment]
hello . 
any suggesrtion ? :)

Thanks

**Comment by norkunas** [comment]
Hello, sorry for late reply.
Are you using youtube-dl binary for windows in an unix environment?

**Comment by garry911** [comment]
Hello , 
Yes  .

**Comment by garry911** [comment]
I am using latest php version in ubuntu Linux .

**Comment by norkunas** [comment]
Then you need to download `youtube-dl` for linux :) https://rg3.github.io/youtube-dl/download.html
```
sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl
```

And then set `$yt->setBinPath('/usr/local/bin/youtube-dl');`

**Comment by norkunas** [comment]
If you need to use the library based on other options, just instantiate a different instances, for example:
```
$videoYt = new YoutubeDl([
    'format' => 'bestvideo',
]);
$video = $videoYt->download('url');

$audioYt = new YoutubeDl([
    'extract-audio' => true,
    'audio-format' => 'mp3',
]);
$audio = $audioYt->download('url');
```

and that's all. :)

**Comment by garry911** [comment]
:) 
setting up this options only  will halt other downloading default  options ? Because I don't want the command programme to download it  each and every time it run .

**Comment by norkunas** [comment]
Sorry, could you be more clear? Because I don't understand know what do you want to do :thinking:

**Comment by norkunas** [comment]
We talked about this in https://github.com/norkunas/youtube-dl-php/issues/72#issuecomment-428814000 you said it's working :)

**Comment by garry911** [comment]
Cool .Yes it is working great. But if I only need to list subs . Actually it is downloading   subtitles . If I want to skip download . Can I ?

**Comment by norkunas** [comment]
I don't think so as I don't see that [youtube-dl](https://github.com/rg3/youtube-dl) itself would support this.

**Comment by garry911** [comment]
Hi , 

Thanks for the help you did . 
I need some suggestion here . 
 I only want the  to list all the available subtitles and no listing of videos format , audios etc . 
 & how can i speed up the listing using your library  ( do i need to add some options ? ) .

Hope you understand what i need . any help is much appreciable .
Thanks .

**Comment by norkunas** [comment]
Hello,

If you don't need to list any other information then don't list :sweat_smile: basically all information is parsed from JSON and it's parsing is fast.

**Comment by garry911** [comment]
😄 cool .

And one More thing
# how to set sub format option as srt , If listing subtitles .
# can we make automatic captions using subtitles i.e  , If I am translating English to French or English to Chinese .
That's it .

Thanks .

**Comment by garry911** [comment]
hello , 
I am using the getSubtitlesList( ) in your library .
the response is no subtitles at all only the formats . can i make the subtitles using these 
options( 'skip-download', 'all-subs' ,'list-subs','write-sub','write-auto-sub' , 'sub-format', 'sub-lang' ) . 
so to get  the max. available subtitles 
I have used the youtube-dl  $yt = new YoutubeDl( ) to call this method & the response is no subtitles only the formats . Thanks in advance .
    [0] => [viki] 1119776v: Downloading video JSON
    [1] => [viki] 1119776v: Downloading video streams JSON
    [2] => Available subtitles for 1119776v:
    [3] => Language formats
    [4] => tr       vtt, srt
    [5] => pt       vtt, srt
    [6] => en       vtt, srt
    [7] => ar       vtt, srt
    [8] => fr       vtt, srt
    [9] => es       vtt, srt
    [10] => de       vtt, srt

**Comment by garry911** [comment]
Hello , 
Yes exactly this is what i want. I am using it like this .  
	 $yt = new YoutubeDl([
					// 'skip-download' => true,
					// 'all-subs' => true,
					// 'list-subs' => true,
					// 'write-sub' => true,
					// 'write-auto-sub' => true,
					// 'sub-format' => 'string',
					// 'sub-lang' => 'string',
					]);
        $video   =  $yt->download($url);

**Comment by norkunas** [comment]
It's impossible to provide to the youtube-dl binary what fields do you need. So when you get the $video just ead the subtitles and ignore other context, as I said earlier it's already fast, you wouldn't notice any difference in speed if other fields wouldn't be denormalized to video model.

**Comment by garry911** [comment]
Thanks .
Yes setting these options gives me all list of  subtitles etc and that means the script is okay in my previous comment .No need to change now . And one more thing . Do this library converts ISO lang codes to language name .

**Comment by norkunas** [comment]
I don't think so, but you can use [Intl](http://php.net/manual/en/locale.getdisplaylanguage.php).

**Comment by garry911** [comment]
Thank you again 😊 . 
What about the script  ?

**Comment by norkunas** [comment]
@garry911 it looks good to me, except the list-subs, it does the discussed thing in https://github.com/norkunas/youtube-dl-php/issues/73#issuecomment-445562283

**Comment by garry911** [comment]
Hello . 

If  i wants to use few more options . where should i add new options .
As i get this error 
" The options "convert-subtitles srt", "sub-format ttml" do not exist. " . 
After adding " 'sub-format ttml' => 'string',
					'convert-subtitles srt' => 'string', " 
these options in this section . 
$yt = new YoutubeDl([
// 'skip-download' => true,
// 'all-subs' => true,
// 'list-subs' => true,
// 'write-sub' => true,
// 'write-auto-sub' => true,
// 'sub-format' => 'string',
// 'sub-lang' => 'string',
]);

Thanks .

**Comment by garry911** [comment]
Hi,
This is working great. Thanks.
But I have some video that " Failed to download " due LC_ALL environment variable and the error is 

WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this. ERROR: This video is not available in your region.

Is there any thing i can set "  LC_ALL "  env variable using this repository,

Thanks.

**Comment by norkunas** [comment]
Hey, this is a [php function](http://php.net/manual/en/function.setlocale.php) and is not related to this library at all, please try it.

**Comment by garry911** [comment]
Hey, Do you have any solution for this Error?
I am failing in executing these videos url. Hope you know some :)

Failed to download: The command "'youtube-dl' 'https://www.viu.com/ott/ph/en-us/vod/42352/Chief%20Kim' '--no-playlist' '--ignore-config' '--write-info-json' '--skip-download' '--write-sub' '--write-auto-sub' '--socket-timeout=2' '--sub-lang=string' '--restrict-filenames'" failed. Exit Code: 1(General error) Working directory: /var/www/html/apps/coresub/public/downloads Output: ================ [viu:ott] 42352: Downloading video info Error Output: ================ ERROR: This video is not available in your region.

**Comment by norkunas** [comment]
Hey @garry911, does it work if you call that command directly in console? If not could you check if that works with some of these options:
```
--geo-verification-proxy URL     Use this proxy to verify the IP address for
                                 some geo-restricted sites. The default
                                 proxy specified by --proxy (or none, if the
                                 option is not present) is used for the
                                 actual downloading.
--geo-bypass                     Bypass geographic restriction via faking
                                 X-Forwarded-For HTTP header
--no-geo-bypass                  Do not bypass geographic restriction via
                                 faking X-Forwarded-For HTTP header
--geo-bypass-country CODE        Force bypass geographic restriction with
                                 explicitly provided two-letter ISO 3166-2
                                 country code
--geo-bypass-ip-block IP_BLOCK   Force bypass geographic restriction with
                                 explicitly provided IP block in CIDR
                                 notation
```

Because as the error says it's not available in your region, so it's the geo restriction IIUC.

**Comment by garry911** [comment]
No running command in console shows me the same error. 
ERROR: This video is not available in your region.

I have tried  adding these options like this.  \Before that i have added these options YoutubeDl.php file.
Things seems not working and the error is same. What URL, CODE and IP_BLOCK can i use to remove these warnings. 
  
 $yt = new YoutubeDl([
					'skip-download' => true,
				        'geo-verification-proxy' => 'string',
					'geo-bypass' => 'string',
                                        'geo-bypass-country' =>
                                    ])

can you please tell me the ryt format to use these option Or any Example.

**Comment by norkunas** [comment]
@garry911 did you try the console command with appending the `--geo-bypass` option?

**Comment by garry911** [comment]
Yes the result was same. Video  not available in your region.

**Comment by norkunas** [comment]
Then sorry because I don't have any suggestions :disappointed:

**Comment by norkunas** [comment]
Probably you'll need to find some proxy then which is not blocked by viu.com

**Comment by garry911** [comment]
Okay. Could you please tell me the right way to do this with correct syntax. As I am getting the error like these option not found. Some other predefined options are found. I think I need to add the not found options in your repository somewhere in YouTube-dl.php.

**Comment by norkunas** [comment]
yes, you could make a pull request, that would be awesome :)

**Comment by garry911** [comment]
Thanks. I will
