### ISSUE TITLE
Donwload from other website

### ISSUE THREAD

**Issue by bkhezry** [norkunas/youtube-dl-php#75]
Hi.
I want to download video of other websites that Youtube dl can download it. but this project returns an Invalid URL error. how can I bypass this checking URL?

**Comment by norkunas** [comment]
Hello @bkhezry, and what's the url exactly? This library has just a single pattern to exclude from downloading soundcloud sets and nothing more, so it should work.

**Comment by bkhezry** [comment]
thanks, @norkunas I used your library instance of the full project. it works. I want to download video from twitter and facebook also that now working.
