### ISSUE TITLE
Audio missing, eventho best is selected

### ISSUE THREAD

**Issue by ThomasVdBerge** [norkunas/youtube-dl-php#78]
I have a problem with the following video:
- https://www.youtube.com/watch?v=M18ktTn-O30

My code looks like this:
```
 $this->youtubeDL = new YoutubeDL([
            'continue' => true,
            'format' => 'best',
        ]);
$this->youtubeDL->download(URL);
```

The video that is downloaded seems to be the best-video one, instead of the best one. Since I keep getting the file without audio. Any way to work around this?

If I choose worst, it gets me only the audio.

**Comment by norkunas** [comment]
Try `bestvideo+bestaudio`
