### ISSUE TITLE
Change pattern to match downloads taking longer than a hour

### ISSUE THREAD

**Issue by sheriffmarley** [norkunas/youtube-dl-php#81]
Sometimes there are situatuions where the download may take more than a hour. If thats the case, the pattern will cut the seconds.
E.g.: [download]   1.0% of 1.20GiB at 210.38KiB/s ETA 01:38:42

With the current pattern only this part is matched,
E.g.: [download]   1.0% of 1.20GiB at 210.38KiB/s ETA 01:38

I suggest to change the eta tag from 
```php
(?<eta>[\d]{2}:[\d]{2})
```

to
```php
(?<eta>[\d:]{2,8})
```
Full pattern
```php
\[download\]\s+(?<percentage>\d+(?:\.\d+)?%)\s+of\s+(?<size>\d+(?:\.\d+)?(?:K|M|G)iB)(?:\s+at\s+(?<speed>\d+(?:\.\d+)?(?:K|M|G)iB/s))?(?:\s+ETA\s+(?<eta>[\d:]{2,8}))
```

**Comment by norkunas** [comment]
Hello @sheriffmarley, would you like to contribute?

**Comment by sheriffmarley** [comment]
Made a pull request https://github.com/norkunas/youtube-dl-php/pull/82
