### ISSUE TITLE
Don't check 'merged into mkv' when recode-video option is given

### ISSUE THREAD

**Issue by dimitricappelle** [norkunas/youtube-dl-php#83]
When the error output contains the 'merged into mkv' warning, YoutubeDl overwrites the _filename by looking for the mkv file. But it the recode-video (ex to mp4) is given, there is no mkv file. This results in an uncaught exception 
`Symfony\Component\Debug\Exception\FatalThrowableError: pathinfo() expects parameter 1 to be string, null given`

**Comment by norkunas** [comment]
Would you like to contribute to fix this?
