### ISSUE TITLE
Issue with Umlauts

### ISSUE THREAD

**Issue by Smythu** [norkunas/youtube-dl-php#86]
If I try to download a video which contains Umlauts in the title I'm getting the following error:

```
file_get_contents(/Users/XXX/Developer/XXX/storage/audio// - Deutsche Aussprache.info.json): failed to open stream: No such file or directory
```

Video: https://www.youtube.com/watch?v=3W8Hijn1zlk

**Comment by Smythu** [comment]
Found that the issue is with other weird characters too for example Hindi

**Comment by norkunas** [comment]
Which php version? You could try to workaround this by using `output` option.
