### ISSUE TITLE
I have this issue, followed all instruction

### ISSUE THREAD

**Issue by jeraldpunx** [norkunas/youtube-dl-php#87]
Warning: proc_open(): CreateProcess failed, error code - 267 in E:\Laragon\www\vanilla\vendor\symfony\process\Process.php on line 337
Symfony\Component\Process\Exception\RuntimeException: Unable to launch a new process. in E:\Laragon\www\vanilla\vendor\symfony\process\Process.php:340 Stack trace: #0 E:\Laragon\www\vanilla\vendor\symfony\process\Process.php(233): Symfony\Component\Process\Process->start(Object(Closure), Array) #1 E:\Laragon\www\vanilla\vendor\symfony\process\Process.php(255): Symfony\Component\Process\Process->run(Object(Closure), Array) #2 E:\Laragon\www\vanilla\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php(156): Symfony\Component\Process\Process->mustRun(Object(Closure)) #3 E:\Laragon\www\vanilla\index.php(26): YoutubeDl\YoutubeDl->download('https://www.you...') #4 {main}

**Comment by norkunas** [comment]
See https://stackoverflow.com/a/30296289
