### ISSUE TITLE
Modify methods from YoutubeDL class to be inherited

### ISSUE THREAD

**Issue by psych0l4st** [norkunas/youtube-dl-php#88]
I am working on with your library and I need to extend YoutubeDL class (some methods are private and can not be inherited (for example handleException or createProcess).

My idea is try to extend some functionallity to adapt for my project, for example the way you use for createProcess or handle some exceptions without coding twice.

The basic idea is create a search engine using the following syntax as a video download: https://www.youtube.com/results?search_query='blablabla' and process the json files and show them to the user (which can choose the file to be downloaded)

Thanks for your work and effort.

**Comment by norkunas** [comment]
All right, made most methods protected, have fun :)

**Comment by psych0l4st** [comment]
Thanks for your fast support. It works like a charm.
