### ISSUE TITLE
How to get the youtube video url without downloading

### ISSUE THREAD

**Issue by wasiqaftab** [norkunas/youtube-dl-php#9]
HI

i see your library its really nice. i need to ask how can i get the video url without downloading it.

Regards
wasiq

**Comment by norkunas** [comment]
Hello @wasiqaftab,

Can you provide more information what do you mean?:) Because before downloading video you already need to know the URL. But if you mean to get information about video without downloading itself you can pass 'skip-download' option.

**Comment by wasiqaftab** [comment]
Hi

Yes this is what i mean i follow your example. But how i skip downloaf

**Comment by norkunas** [comment]
@wasiqaftab 

```php
$dl = new YoutubeDl(['skip-download' => true]);
$dl->download('url of video');
```

In this way download will be skipped but it's information will be mapped to entities.

**Comment by wasiqaftab** [comment]
@norkunas it works thanks alot

**Comment by norkunas** [comment]
@wasiqaftab good :wink:

**Comment by norkunas** [comment]
@wasiqaftab can you close the issue then?

**Comment by wasiqaftab** [comment]
Yes sure will do
