### ISSUE TITLE
Issue downloading video to shared folder

### ISSUE THREAD

**Issue by jacksnchz** [norkunas/youtube-dl-php#90]
Hello,

I have a trouble if the download directory is a shared folder (UNC path/samba).

Example code:

```
$dl = new YoutubeDl([
    'format' => 'bestvideo',
]);
$dl->setBinPath("C:\scripts\youtube-dl.exe");
$dl->setDownloadPath(addslashes("\\192.168.1.1\videos"));
$video = $dl->download('https://www.youtube.com/watch?v=oDAw7vW7H0c');

```

Error:

`<b>Warning</b>:  file_get_contents(\\192.168.1.1\videos\oDAw7vW7H0c.info.json): failed to open stream: No such file or directory in <b>C:\projects\www\yt-downloader\vendor\norkunas\youtube-dl-php\src\YoutubeDl.php</b> on line <b>191</b><br />`

I have been checking YoutubeDL class and the download directory is set internally  also as cwd for process class before proc_open, and finally the process can not write on the path specified, but the processDownload is waiting the correct folder defined by user with no content so the code returns an error.

Checklist completed:
- Process class detects the folder as valid before it runs.
- The directory has full permissions enabled for all users.
- Running youtube-dl.exe file from command line works perfect.
- I have run Apache with local & admin users.
- All test have been made with Windows 10 with PHP 7.1.20

I have tried to put the download path inside the output template and it works (I have extend download method from YoutubeDl class and I have made some modifications for read the json file from the correct directory and the process cwd is not set, using default value instead)

I think that can be interesting to check if the problem is mine or a small bug.

The command line used from cmd:

> youtube-dl.exe --write-info-json --ignore-config --no-playlist "https://www.youtube.com/watch?v=oDAw7vW7H0c" -o "\\\192.168.1.1\videos\%(title)s.%(ext)s"

Thanks!

**Comment by norkunas** [comment]
Hello,

I don't have any possibility to test with shared folders so I've just checked using `output` option and providing download path to it while skipping setting the working dir for the process and it properly works.

So probably the best solution would be to add an option to disable setting cwd, so you could configure your `output` option with your download path.
WDYT?

**Comment by psych0l4st** [comment]
> Hello,
> 
> I don't have any possibility to test with shared folders so I've just checked using `output` option and providing download path to it while skipping setting the working dir for the process and it properly works.
> 
> So probably the best solution would be to add an option to disable setting cwd, so you could configure your `output` option with your download path.
> WDYT?

Hello,

Yes, I was thinking about that (modify the logic how the download path is provided), I have made a fork and if the changes are sucessfull I'll do a PR.

Thanks!
