### ISSUE TITLE
Downloads audio in  'webm' format

### ISSUE THREAD

**Issue by jnrklbv** [norkunas/youtube-dl-php#93]
hey there. I am using your library to download only audio from youtube video and i really need your help. the thing is it downloads audio but in 'webm' format but i need 'mp3'. while downloading it gives a warning: unable to obtain file audio codec with ffprobe. however when i try to do it in terminal it works fine. (I also tried to update ffmpeg it didn't work). here's the code:

public function downloadAudio(Request $request)
    {

        $dl = new YoutubeDl([
            'extract-audio' => true,
            'audio-format' => 'mp3',
            'audio-quality' => 0, // best
            'prefer-ffmpeg'=>true,
            'ffmpeg-location' => '/usr/bin/ffmpeg',
            'output' => '%(title)s.%(ext)s',
        ]);
        $dl->setDownloadPath('/home/user/downloads');
        $dl->setBinPath('/usr/local/bin/youtube-dl');
        $videolink=$request['link'];       
        $video = $dl->download($videolink);             
    }

and here's an output:

The command "'/usr/local/bin/youtube-dl' 'https://www.youtube.com/watch?v=OMOGaugKpzs' '--no-playlist' '--ignore-config' '--write-info-json' '--extract-audio' '--audio-format=best' '--audio-quality=0' '--prefer-ffmpeg' '--ffmpeg-location=/usr/bin/ffmpeg' '--output=%(title)s.%(ext)s'" failed.\n ◀
\n
Exit Code: 1(General error)\n
\n
Working directory: /home/user/downloads\n
\n
Output:\n
================\n
[youtube] OMOGaugKpzs: Downloading webpage\n
[youtube] OMOGaugKpzs: Downloading video info webpage\n
[youtube] Downloading just video OMOGaugKpzs because of --no-playlist\n
[info] Writing video description metadata as JSON to: The Police - Every Breath You Take (Official Music Video).info.json\n
[download] Destination: The Police - Every Breath You Take (Official Music Video).webm\n\r
[download]   0.0% of 3.60MiB at Unknown speed ETA Unknown ETA\r
[download]   0.1% of 3.60MiB at  2.47MiB/s ETA 00:01\r
[download]   0.2% of 3.60MiB at  4.14MiB/ ▶
\n
\n
Error Output:\n
================\n
ERROR: WARNING: unable to obtain file audio codec with ffprobe\n

thank you in advance:)

**Comment by norkunas** [comment]
Hello, for me it works as expected:

```
<?php
require __DIR__.'/vendor/autoload.php';

$dl = new \YoutubeDl\YoutubeDl([
    'extract-audio' => true,
    'audio-format' => 'mp3',
    'audio-quality' => 0, // best
    'prefer-ffmpeg'=>true,
    'ffmpeg-location' => '/usr/bin/ffmpeg',
    'output' => '%(title)s.%(ext)s',
]);
$dl->setDownloadPath('/home/norkunas/Downloads');
$dl->setBinPath('/usr/local/bin/youtube-dl');
$dl->debug(function ($type, $buffer) {
    if (\Symfony\Component\Process\Process::ERR === $type) {
        echo 'ERR > ' . $buffer;
    } else {
        echo 'OUT > ' . $buffer;
    }
});

$dl->download('https://www.youtube.com/watch?v=OMOGaugKpzs');

OUT > [youtube] OMOGaugKpzs: Downloading webpage
OUT > [youtube] OMOGaugKpzs: Downloading video info webpage
OUT > [youtube] Downloading just video OMOGaugKpzs because of --no-playlist
OUT > [info] Writing video description metadata as JSON to: The Police - Every Breath You Take (Official Music Video).info.json
OUT > [download] Destination: The Police - Every Breath You Take (Official Music Video).webm
[download] 100% of 3.60MiB in 00:0184MiB/s ETA 00:00OUT >  
OUT > [ffmpeg] Destination: The Police - Every Breath You Take (Official Music Video).mp3
OUT > Deleting original file The Police - Every Breath You Take (Official Music Video).webm (pass -k to keep)
```

Please make sure all your configuration values are valid :)

**Comment by jnrklbv** [comment]
thank you for your reply! :)
I know, this might be the dumbest question ever. Which configuration values should I check? I followed all instruction while installing youtube-dl and your library. 
In terminal everything works fine, though. I just don't get it, why it downloads in webm format...

**Comment by norkunas** [comment]
It downloads in webm, because youtube provides it. The conversion is done with ffmpeg if you configure to mp3 extract as mp3. Does it properly convert to mp3 properly when you run yt-dl in terminal?

**Comment by jnrklbv** [comment]
yes, it works properly in terminal... that's the command I use in terminal: youtube-dl -x --audio-format mp3 videoURL

**Comment by norkunas** [comment]
Can you check if this works for you?:
```
<?php

require __DIR__.'/vendor/autoload.php';

echo (new \Symfony\Component\Process\Process('ffprobe -version'))->mustRun()->getOutput();
```

**Comment by jnrklbv** [comment]
I'm using Laravel in this project. Is that gonna be ok?
I got this: 

The command "ffprobe -version" failed.\n
\n
Exit Code: 1(General error)\n
\n
Working directory: /opt/lampp/htdocs/youtube-dl/public\n
\n
Output:\n
================\n
\n
\n
Error Output:\n
================\n
ffprobe: /opt/lampp/lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/x86_64-linux-gnu/libjack.so.0)\n
ffprobe: /opt/lampp/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libjack.so.0)\n
ffprobe: /opt/lampp/lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/x86_64-linux-gnu/libzmq.so.5)\n
ffprobe: /opt/lampp/lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/x86_64-linux-gnu/libzmq.so.5)\n
ffprobe: /opt/lampp/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libzmq.so.5)\n
ffprobe: /opt/lampp/lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/x86_64-linux-gnu/librubberband.so.2)\n
ffprobe: /opt/lampp/lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/x86_64-linux-gnu/librubberband.so.2)\n
ffprobe: /opt/lampp/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/librubberband.so.2)\n
ffprobe: /opt/lampp/lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/x86_64-linux-gnu/libopenmpt.so.0)\n
ffprobe: /opt/lampp/lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/x86_64-linux-gnu/libopenmpt.so.0)\n
ffprobe: /opt/lampp/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libopenmpt.so.0)\n
ffprobe: /opt/lampp/lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/x86_64-linux-gnu/libgme.so.0)\n
ffprobe: /opt/lampp/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libchromaprint.so.1)\n
ffprobe: /opt/lampp/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libsnappy.so.1)\n
ffprobe: /opt/lampp/lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/x86_64-linux-gnu/libsnappy.so.1)\n
ffprobe: /opt/lampp/lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/x86_64-linux-gnu/libnorm.so.1)\n
ffprobe: /opt/lampp/lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/x86_64-linux-gnu/libnorm.so.1)\n

**Comment by norkunas** [comment]
Hmm. Maybe reinstall ffmpeg? I think something is wrong with your binary dependencies

**Comment by jnrklbv** [comment]
reinstalled ffmpeg, didn't work :(

**Comment by norkunas** [comment]
Also you could try using [avconv](https://libav.org/) instead of ffmpeg, otherwise I'm out of options to help you :disappointed:

**Comment by jnrklbv** [comment]
I'll try that.. Thanks anyway :)

**Comment by norkunas** [comment]
Also about that error you could check here https://askubuntu.com/a/582910

**Comment by jnrklbv** [comment]
hey there again! I found a solution finally:)... First of all, I followed all instruction in the link you had sent previously, but it didn't change anything... and then I executed this command in the terminal and everything worked:
sudo mv /opt/lampp/lib/libstdc++.so.6 /opt/lampp/lib/libstdc++.so.6.orig

**Comment by norkunas** [comment]
Hey, that's a good news! :)
