### ISSUE TITLE
Vimeo onprogress not firing

### ISSUE THREAD

**Issue by gromiak** [norkunas/youtube-dl-php#94]
Hi, when i try to download sample vimeo files it downloads but not firing onProgress callback. Other sites like youtube etc fires onProgress correctly.
I suppose the error is in some sort of parsing where downloading m3u8 files

**Comment by norkunas** [comment]
Hello, maybe it use some sort of different progress format? How does it look in console? Would you like to contribute fix? :slightly_smiling_face:
