### ISSUE TITLE
 how to use proxies with youtube-dl-php

### ISSUE THREAD

**Issue by YuriBarzola** [norkunas/youtube-dl-php#98]
I did it that way but it didn't work
```

$dl = new YoutubeDl(array(
                        'proxy'=>'XXX.XXX.XXX.XXX:3128',
                        'extract-audio' => true,
                        'audio-format' => 'mp3',
                        'audio-quality' => 0, 
                        'output' => '%(id)s.%(ext)s',
                        //'ffmpeg-location' => '/usr/local/bin/ffmpeg'
                ));

```

**Comment by savproga** [comment]
You can try to use proxy configuration via configuration file: [youtube-dl documentation](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#configuration) or use [socks5](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#network-options)
