### ISSUE TITLE
Run youtube-dl process detached

### ISSUE THREAD

**Issue by psociety** [norkunas/youtube-dl-php#99]
I would like to give `youtube-dl` the order to start downloading a video in background, rather than waiting for it to finish loading the page as is doing right now.
Is it possible? I didn't find any reference in the docs : s

**Comment by norkunas** [comment]
Hello, this is not supported directly in the lib, but you could extend and update process running to do that in background.

**Comment by psociety** [comment]
Oops, i forgot to close this issue, i switched to a working lib.
